//! EDGE-10: Dynamic tool generation from natural language.
//!
//! [`ToolBuilder`] accepts a natural-language description, constructs an LLM
//! prompt, parses the response into a [`GeneratedTool`], optionally compiles it
//! to WebAssembly via `rustc --target wasm32-wasi`, and submits it for operator
//! approval before it is registered with the [`ToolGate`].
//!
//! # Lifecycle
//! ```text
//! describe("check if a URL is reachable")
//!   → generation_prompt()           — builds an LLM-ready prompt
//!   → parse_generation_response()   — extracts JSON from LLM output
//!   → compile_to_wasm() (optional)  — rustc + wasm32-wasi target
//!   → submit_for_approval()         — queued; operator must approve
//!   → approve_tool()                — validates wasm if present,
//!                                     registers + allows in ToolGate
//! ```
//!
//! # Compilation
//! Compilation is opportunistic — if `rustc` and the `wasm32-wasi` target are
//! not available, [`compile_to_wasm`] returns
//! [`ToolBuildError::CompilationUnavailable`] and callers should continue with
//! `wasm_bytes: None` (source is stored; WASM can be produced later).
//!
//! # Storage
//! Approved tools with WASM binaries are persisted as `<name>.wasm` files under
//! `tools_dir` (default `~/.lumina/tools/`).  On restart, the gate can reload
//! them from disk via [`ToolBuilder::list_approved_tools`].

use crate::error::Result;
use crate::tool_gate::ToolGate;
use crate::tool_types::WasmCapability;
use crate::wasm_sandbox::WasmSandbox;
use std::io::Write as IoWrite;
use std::path::PathBuf;
use std::sync::Mutex;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum compiled WASM binary size accepted (10 MiB).
const MAX_WASM_SIZE_BYTES: usize = 10 * 1024 * 1024;

// ---------------------------------------------------------------------------
// GeneratedTool
// ---------------------------------------------------------------------------

/// A tool synthesised from a natural-language description.
///
/// Holds all metadata required to validate, store, and register the tool.
#[derive(Debug, Clone)]
pub struct GeneratedTool {
    /// Short, unique machine-readable identifier (e.g. `"check_url"`).
    pub name: String,
    /// Human-readable description surfaced to the LLM and the operator.
    pub description: String,
    /// JSON Schema for the tool's arguments (OpenAI/MCP format).
    pub argument_schema: serde_json::Value,
    /// Declared WASM capability requirements (e.g. `["network"]`).
    pub capabilities: Vec<String>,
    /// Pre-compiled WASM binary, if compilation succeeded.
    pub wasm_bytes: Option<Vec<u8>>,
    /// Original Rust source code generated by the LLM.
    pub source_code: String,
    /// Whether the operator has approved this tool for execution.
    pub approved: bool,
    /// Unix epoch seconds as a string (e.g. `"1717584000"`).
    pub created_at: String,
}

// ---------------------------------------------------------------------------
// ToolBuildError
// ---------------------------------------------------------------------------

/// Errors that can occur during dynamic tool generation and approval.
#[derive(Debug)]
pub enum ToolBuildError {
    /// `rustc` or the `wasm32-wasi` target is not available on this machine.
    CompilationUnavailable,
    /// `rustc` returned a non-zero exit code; the message contains stderr.
    CompilationFailed(String),
    /// The generated tool metadata or source code did not pass validation.
    ValidationFailed(String),
    /// The compiled WASM binary exceeds the 10 MiB size limit.
    OversizedWasm {
        /// Actual binary size in bytes.
        size_bytes: usize,
    },
    /// The tool is in the pending queue and has not yet been approved.
    PendingApproval {
        /// Name of the unapproved tool.
        tool_name: String,
    },
}

impl std::fmt::Display for ToolBuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ToolBuildError::CompilationUnavailable => write!(
                f,
                "Dynamic tool compilation is unavailable: rustc or wasm32-wasi target not found"
            ),
            ToolBuildError::CompilationFailed(msg) => {
                write!(f, "Compilation failed: {msg}")
            }
            ToolBuildError::ValidationFailed(msg) => {
                write!(f, "Tool validation failed: {msg}")
            }
            ToolBuildError::OversizedWasm { size_bytes } => write!(
                f,
                "Compiled WASM binary ({size_bytes} bytes) exceeds the 10 MiB limit"
            ),
            ToolBuildError::PendingApproval { tool_name } => {
                write!(f, "Tool '{tool_name}' is awaiting operator approval")
            }
        }
    }
}

impl std::error::Error for ToolBuildError {}

// ---------------------------------------------------------------------------
// ToolBuilder
// ---------------------------------------------------------------------------

/// Manages the lifecycle of dynamically generated tools.
pub struct ToolBuilder {
    /// Directory where approved `.wasm` binaries are stored.
    tools_dir: PathBuf,
    /// Queue of tools awaiting operator approval.
    pending: Mutex<Vec<GeneratedTool>>,
}

impl ToolBuilder {
    /// Create a new [`ToolBuilder`] that stores WASM files under `tools_dir`.
    ///
    /// The directory is created if it does not already exist.
    pub fn new(tools_dir: PathBuf) -> Result<Self> {
        std::fs::create_dir_all(&tools_dir)?;
        Ok(Self {
            tools_dir,
            pending: Mutex::new(Vec::new()),
        })
    }

    /// Returns the default tool storage directory: `~/.lumina/tools/`.
    pub fn default_tools_dir() -> PathBuf {
        dirs::home_dir()
            .unwrap_or_else(|| PathBuf::from("/tmp"))
            .join(".lumina")
            .join("tools")
    }

    // -----------------------------------------------------------------------
    // Prompt construction
    // -----------------------------------------------------------------------

    /// Build an LLM prompt that requests a tool definition for `description`.
    ///
    /// `existing_tools` is the list of already-registered tool names so the LLM
    /// can avoid duplicating them.  The prompt instructs the model to respond
    /// with a single JSON object.
    pub fn generation_prompt(description: &str, existing_tools: &[String]) -> String {
        let tool_list = if existing_tools.is_empty() {
            "none".to_string()
        } else {
            existing_tools.join(", ")
        };

        format!(
            r#"You are a Rust tool-generation assistant. The operator needs a new tool.

Description: {description}

Existing tools (do not duplicate): {tool_list}

Respond with exactly one JSON object and nothing else. The object must have these fields:

{{
  "name": "<snake_case identifier>",
  "description": "<one sentence description>",
  "argument_schema": {{ <JSON Schema object for the tool's arguments> }},
  "capabilities": ["<list of required capabilities: network, filesystem, env, stdout>"],
  "source_code": "<complete Rust function body as a string>"
}}

Rules:
- name must be non-empty snake_case
- source_code must be non-empty valid Rust
- capabilities must only reference: network, filesystem, env, stdout
- argument_schema must be a valid JSON Schema object
- Do not include any explanation outside the JSON object"#
        )
    }

    // -----------------------------------------------------------------------
    // Response parsing
    // -----------------------------------------------------------------------

    /// Parse a JSON tool definition out of raw LLM output.
    ///
    /// The LLM may prefix or suffix the JSON with prose.  This function finds
    /// the first `{` and last `}` in the output and attempts to parse the
    /// substring as a [`GeneratedTool`].
    ///
    /// Returns `None` if:
    /// - no JSON object is found in the output,
    /// - the JSON cannot be parsed,
    /// - the `name` field is not a valid snake_case identifier,
    /// - the `source_code` field is empty.
    pub fn parse_generation_response(llm_output: &str) -> Option<GeneratedTool> {
        // Find outermost JSON object boundaries
        let start = llm_output.find('{')?;
        let end = llm_output.rfind('}')?;
        if end < start {
            return None;
        }

        let json_slice = &llm_output[start..=end];
        let value: serde_json::Value = serde_json::from_str(json_slice).ok()?;
        let obj = value.as_object()?;

        let name = obj.get("name")?.as_str()?.trim().to_string();
        if !is_valid_tool_name(&name) {
            return None;
        }

        let description = obj
            .get("description")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .trim()
            .to_string();

        let argument_schema = obj
            .get("argument_schema")
            .cloned()
            .unwrap_or_else(|| serde_json::json!({}));

        let capabilities: Vec<String> = obj
            .get("capabilities")
            .and_then(|v| v.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|item| item.as_str())
                    .map(|s| s.to_string())
                    .collect()
            })
            .unwrap_or_default();

        let source_code = obj.get("source_code")?.as_str()?.trim().to_string();
        if source_code.is_empty() {
            return None;
        }

        let created_at = unix_epoch_secs();

        Some(GeneratedTool {
            name,
            description,
            argument_schema,
            capabilities,
            wasm_bytes: None,
            source_code,
            approved: false,
            created_at,
        })
    }

    // -----------------------------------------------------------------------
    // WASM compilation
    // -----------------------------------------------------------------------

    /// Attempt to compile `source` Rust code to a `wasm32-wasi` binary.
    ///
    /// # Return values
    /// - `Ok(bytes)` — compilation succeeded and the binary is under 10 MiB.
    /// - `Err(CompilationUnavailable)` — `rustc` or the wasm32 target is absent.
    /// - `Err(CompilationFailed(…))` — `rustc` reported errors.
    /// - `Err(OversizedWasm { … })` — binary exceeds 10 MiB.
    pub fn compile_to_wasm(source: &str) -> std::result::Result<Vec<u8>, ToolBuildError> {
        // 1. Check that rustc is on PATH
        let rustc_check = std::process::Command::new("rustc").arg("--version").output();
        if rustc_check.is_err() {
            return Err(ToolBuildError::CompilationUnavailable);
        }

        // 2. Check that the wasm32-wasi target is installed
        let target_check = std::process::Command::new("rustup")
            .args(["target", "list", "--installed"])
            .output();

        let wasm_available = match &target_check {
            Ok(out) => {
                let stdout = String::from_utf8_lossy(&out.stdout);
                stdout.contains("wasm32-wasi") || stdout.contains("wasm32-wasip1")
            }
            Err(_) => {
                // rustup not available — try a direct check via rustc
                false
            }
        };

        if !wasm_available {
            // Also check via rustc directly (some setups don't use rustup)
            let direct_check = std::process::Command::new("rustc")
                .args(["--print", "target-list"])
                .output();
            let wasm_direct = direct_check
                .ok()
                .map(|out| {
                    let s = String::from_utf8_lossy(&out.stdout);
                    s.contains("wasm32-wasi") || s.contains("wasm32-wasip1")
                })
                .unwrap_or(false);

            if !wasm_direct {
                return Err(ToolBuildError::CompilationUnavailable);
            }
        }

        // 3. Write source to a temp file (RAII cleanup via TempDir)
        let tmp_dir =
            tempfile::tempdir().map_err(|e| ToolBuildError::CompilationFailed(e.to_string()))?;
        let src_path = tmp_dir.path().join("tool.rs");
        let out_path = tmp_dir.path().join("tool.wasm");

        {
            let mut f = std::fs::File::create(&src_path)
                .map_err(|e| ToolBuildError::CompilationFailed(e.to_string()))?;
            f.write_all(source.as_bytes())
                .map_err(|e| ToolBuildError::CompilationFailed(e.to_string()))?;
        }

        // 4. Compile
        let compile_result = std::process::Command::new("rustc")
            .args([
                "--target",
                "wasm32-wasi",
                "--crate-type",
                "cdylib",
                "-o",
                out_path.to_str().unwrap_or("tool.wasm"),
                src_path.to_str().unwrap_or("tool.rs"),
            ])
            .output()
            .map_err(|e| ToolBuildError::CompilationFailed(e.to_string()))?;

        if !compile_result.status.success() {
            let stderr = String::from_utf8_lossy(&compile_result.stderr).to_string();
            return Err(ToolBuildError::CompilationFailed(stderr));
        }

        // 5. Read the binary
        let wasm_bytes = std::fs::read(&out_path)
            .map_err(|e| ToolBuildError::CompilationFailed(e.to_string()))?;

        // 6. Size check
        if wasm_bytes.len() > MAX_WASM_SIZE_BYTES {
            return Err(ToolBuildError::OversizedWasm {
                size_bytes: wasm_bytes.len(),
            });
        }

        Ok(wasm_bytes)
    }

    // -----------------------------------------------------------------------
    // Approval workflow
    // -----------------------------------------------------------------------

    /// Submit a [`GeneratedTool`] for operator approval.
    ///
    /// Rejects submission if a tool with the same name is already pending
    /// (prevents duplicate entries in the queue).
    ///
    /// Returns a human-readable message suitable for posting to the operator
    /// channel (Matrix, etc.).
    pub fn submit_for_approval(&self, tool: GeneratedTool) -> String {
        let name = tool.name.clone();
        let caps = if tool.capabilities.is_empty() {
            "none".to_string()
        } else {
            tool.capabilities.join(", ")
        };

        let mut pending = self.pending.lock().unwrap();

        // Deduplicate by name: if a pending tool with the same name exists,
        // replace it with the newer submission (last-writer-wins semantics).
        if let Some(pos) = pending.iter().position(|t| t.name == name) {
            pending[pos] = tool;
        } else {
            pending.push(tool);
        }

        format!(
            "New tool: {name}. Capabilities: [{caps}]. Reply approve {name} to enable."
        )
    }

    /// Approve a pending tool by name.
    ///
    /// 1. Removes the tool from the pending queue.
    /// 2. If the tool has a WASM binary:
    ///    a. Validates it runs safely in a zero-capability sandbox (catches panics
    ///       and malformed binaries before they reach production).
    ///    b. Writes the binary to `<tools_dir>/<name>.wasm` with a path-traversal
    ///       guard (canonicalize + prefix check).
    /// 3. Converts declared capability strings to [`WasmCapability`] values and
    ///    registers them on the gate so sandbox enforcement works correctly.
    /// 4. Calls [`ToolGate::register_dynamic_tool`] to register and allow the tool.
    /// 5. Sets `approved = true` on the tool record (useful for serialization).
    ///
    /// Returns [`ToolBuildError::PendingApproval`] if no tool with that name is
    /// found in the queue.
    pub fn approve_tool(
        &self,
        name: &str,
        gate: &ToolGate,
    ) -> std::result::Result<(), ToolBuildError> {
        // Reject names that haven't been validated.
        if !is_valid_tool_name(name) {
            return Err(ToolBuildError::ValidationFailed(format!(
                "Tool name '{name}' is not a valid snake_case identifier"
            )));
        }

        // Remove from pending and mark as approved.
        let mut tool = {
            let mut pending = self.pending.lock().unwrap();
            let pos = pending
                .iter()
                .position(|t| t.name == name)
                .ok_or_else(|| ToolBuildError::PendingApproval {
                    tool_name: name.to_string(),
                })?;
            pending.remove(pos)
        };
        tool.approved = true;

        // If a WASM binary is present, validate it before persisting.
        if let Some(ref bytes) = tool.wasm_bytes {
            // Run the binary in a zero-capability sandbox to catch panics /
            // malformed WASM before the tool reaches production use.
            if let Ok(sandbox) = WasmSandbox::new() {
                sandbox.execute(bytes, "", &[], None).map_err(|e| {
                    ToolBuildError::ValidationFailed(format!(
                        "WASM sandbox validation failed for '{name}': {e}"
                    ))
                })?;
            }
            // (If sandbox creation fails, we proceed — execution environment
            // may not support WASM; the binary is still stored for later use.)

            // Persist with path-traversal guard.
            let wasm_path = self.tools_dir.join(format!("{}.wasm", tool.name));
            let canon_dir = self.tools_dir.canonicalize().map_err(|e| {
                ToolBuildError::CompilationFailed(format!("Cannot canonicalize tools_dir: {e}"))
            })?;
            let canon_wasm = {
                let parent = wasm_path.parent().unwrap_or(&self.tools_dir);
                let canon_parent = parent.canonicalize().map_err(|e| {
                    ToolBuildError::CompilationFailed(format!(
                        "Cannot canonicalize wasm parent dir: {e}"
                    ))
                })?;
                canon_parent.join(wasm_path.file_name().unwrap_or_default())
            };
            if !canon_wasm.starts_with(&canon_dir) {
                return Err(ToolBuildError::ValidationFailed(format!(
                    "Tool name '{name}' would escape the tools directory (path traversal detected)"
                )));
            }
            std::fs::write(&canon_wasm, bytes).map_err(|e| {
                ToolBuildError::CompilationFailed(format!("Failed to write wasm: {e}"))
            })?;
        }

        // Map declared capability strings → WasmCapability and register them
        // on the gate so that sandbox enforcement uses the correct grants.
        let wasm_caps = capabilities_from_strings(&tool.capabilities);
        if !wasm_caps.is_empty() {
            gate.set_tool_capabilities(tool.name.clone(), wasm_caps);
        }

        // Register and allow the tool (read-only) via the gate's dedicated method.
        gate.register_dynamic_tool(&tool.name, &tool.description, tool.argument_schema.clone());

        Ok(())
    }

    /// Return the list of tools currently awaiting operator approval.
    pub fn list_pending(&self) -> Vec<GeneratedTool> {
        self.pending.lock().unwrap().clone()
    }

    /// Scan `tools_dir` for approved `.wasm` files and return their base names.
    ///
    /// The returned strings are the tool names (filename without `.wasm`).
    pub fn list_approved_tools(&self) -> Result<Vec<String>> {
        let mut names = Vec::new();
        for entry in std::fs::read_dir(&self.tools_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("wasm") {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    names.push(stem.to_string());
                }
            }
        }
        Ok(names)
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Validate that `name` is a safe, filesystem-friendly tool identifier.
///
/// Accepted pattern: `[a-z][a-z0-9_]{0,63}` — lowercase ASCII, starts with
/// a letter, at most 64 characters total.  This prevents path traversal
/// (`../../etc/...`), spaces, and other problematic characters.
fn is_valid_tool_name(name: &str) -> bool {
    if name.is_empty() || name.len() > 64 {
        return false;
    }
    let mut chars = name.chars();
    let first = match chars.next() {
        Some(c) => c,
        None => return false,
    };
    if !first.is_ascii_lowercase() {
        return false;
    }
    chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
}

/// Convert capability name strings (e.g. `"network"`) to [`WasmCapability`] variants.
///
/// Unknown capability strings are silently ignored; callers should validate
/// capability names before submission if strict checking is needed.
fn capabilities_from_strings(caps: &[String]) -> Vec<WasmCapability> {
    caps.iter()
        .filter_map(|s| match s.as_str() {
            "stdout" => Some(WasmCapability::Stdout),
            "network" => Some(WasmCapability::Network { hosts: vec![] }),
            "filesystem" => Some(WasmCapability::Filesystem { paths: vec![] }),
            "env" => Some(WasmCapability::Env { keys: vec![] }),
            _ => None,
        })
        .collect()
}

/// Return a Unix epoch seconds string as a creation timestamp.
///
/// This avoids adding chrono as a hard dependency just for tool metadata.
fn unix_epoch_secs() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format!("{secs}")
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tool_gate::ToolGate;

    // ── Test 1: generation_prompt_contains_description ────────────────────

    #[test]
    fn generation_prompt_contains_description() {
        let desc = "check if a website is reachable";
        let prompt = ToolBuilder::generation_prompt(desc, &[]);
        assert!(
            prompt.contains(desc),
            "Prompt must embed the description: {prompt}"
        );
    }

    // ── Test 2: parse_valid_json ──────────────────────────────────────────

    #[test]
    fn parse_valid_json() {
        let llm_output = r#"{
            "name": "check_url",
            "description": "Check if a URL returns HTTP 200",
            "argument_schema": {"type": "object", "properties": {"url": {"type": "string"}}},
            "capabilities": ["network", "stdout"],
            "source_code": "fn check_url(url: &str) -> bool { true }"
        }"#;

        let tool = ToolBuilder::parse_generation_response(llm_output);
        assert!(tool.is_some(), "Should parse valid JSON");
        let t = tool.unwrap();
        assert_eq!(t.name, "check_url");
        assert_eq!(t.capabilities, vec!["network", "stdout"]);
        assert!(!t.source_code.is_empty());
        assert!(!t.approved);
    }

    // ── Test 3: parse_invalid_returns_none ───────────────────────────────

    #[test]
    fn parse_invalid_returns_none() {
        assert!(ToolBuilder::parse_generation_response("not json at all").is_none());
        assert!(ToolBuilder::parse_generation_response("").is_none());
        assert!(ToolBuilder::parse_generation_response("{ invalid }").is_none());
    }

    // ── Test 4: parse_extracts_from_prose ────────────────────────────────

    #[test]
    fn parse_extracts_from_prose() {
        let llm_output = r#"Sure! Here is the tool definition you asked for:

{
    "name": "ping_host",
    "description": "Ping a hostname and return latency",
    "argument_schema": {"type": "object"},
    "capabilities": ["network"],
    "source_code": "fn ping(host: &str) -> u64 { 0 }"
}

Let me know if you need changes."#;

        let tool = ToolBuilder::parse_generation_response(llm_output);
        assert!(tool.is_some(), "Should extract JSON embedded in prose");
        assert_eq!(tool.unwrap().name, "ping_host");
    }

    // ── Test 5: compile_unavailable_graceful ─────────────────────────────

    #[test]
    fn compile_unavailable_graceful() {
        // We do not require wasm32-wasi in the test environment.
        // The function should return either Ok (if the target is present) or
        // a typed error — but it must never panic.
        let source = r#"
            #[no_mangle]
            pub extern "C" fn run() {}
        "#;
        let result = ToolBuilder::compile_to_wasm(source);
        // Accept any outcome except a panic
        match result {
            Ok(bytes) => assert!(!bytes.is_empty()),
            Err(ToolBuildError::CompilationUnavailable) => { /* expected on CI */ }
            Err(ToolBuildError::CompilationFailed(_)) => { /* rustc present but error */ }
            Err(other) => panic!("Unexpected error: {other}"),
        }
    }

    // ── Test 6: tool_not_in_gate_before_approval ─────────────────────────

    #[test]
    fn tool_not_in_gate_before_approval() {
        let tmp = tempfile::tempdir().unwrap();
        let builder = ToolBuilder::new(tmp.path().to_path_buf()).unwrap();
        let gate = ToolGate::new();

        let tool = GeneratedTool {
            name: "not_approved_yet".to_string(),
            description: "A test tool".to_string(),
            argument_schema: serde_json::json!({}),
            capabilities: vec![],
            wasm_bytes: None,
            source_code: "fn main() {}".to_string(),
            approved: false,
            created_at: "0".to_string(),
        };

        builder.submit_for_approval(tool);

        // Gate must NOT have this tool registered before approval
        assert!(
            gate.get_tool_definition("not_approved_yet").is_none(),
            "Tool must not be in gate before approval"
        );
    }

    // ── Test 7: approve_registers_with_gate ──────────────────────────────

    #[test]
    fn approve_registers_with_gate() {
        let tmp = tempfile::tempdir().unwrap();
        let builder = ToolBuilder::new(tmp.path().to_path_buf()).unwrap();
        let gate = ToolGate::new();

        let tool = GeneratedTool {
            name: "my_approved_tool".to_string(),
            description: "Does something useful".to_string(),
            argument_schema: serde_json::json!({"type": "object"}),
            capabilities: vec!["stdout".to_string()],
            wasm_bytes: None,
            source_code: "fn main() {}".to_string(),
            approved: false,
            created_at: "0".to_string(),
        };

        builder.submit_for_approval(tool);
        builder.approve_tool("my_approved_tool", &gate).unwrap();

        // Tool must now be registered in the gate
        assert!(
            gate.get_tool_definition("my_approved_tool").is_some(),
            "Approved tool must appear in gate"
        );

        // Tool must be in the allowlist (ReadOnly)
        let allowed = gate.get_allowed_tools();
        assert!(
            allowed.iter().any(|(n, _)| n == "my_approved_tool"),
            "Approved tool must be in allowlist"
        );
    }

    // ── Test 8: list_pending_shows_submitted ─────────────────────────────

    #[test]
    fn list_pending_shows_submitted() {
        let tmp = tempfile::tempdir().unwrap();
        let builder = ToolBuilder::new(tmp.path().to_path_buf()).unwrap();

        assert!(builder.list_pending().is_empty());

        let tool = GeneratedTool {
            name: "pending_one".to_string(),
            description: "Pending tool".to_string(),
            argument_schema: serde_json::json!({}),
            capabilities: vec![],
            wasm_bytes: None,
            source_code: "fn main() {}".to_string(),
            approved: false,
            created_at: "0".to_string(),
        };

        builder.submit_for_approval(tool);

        let pending = builder.list_pending();
        assert_eq!(pending.len(), 1);
        assert_eq!(pending[0].name, "pending_one");
    }

    // ── Test 9: oversized_check ───────────────────────────────────────────

    #[test]
    fn oversized_check() {
        // Verify OversizedWasm variant is constructable and error message
        // mentions both the limit and the actual size.
        let err = ToolBuildError::OversizedWasm {
            size_bytes: MAX_WASM_SIZE_BYTES + 1,
        };
        let msg = err.to_string();
        assert!(msg.contains("10 MiB"), "Error should mention the limit: {msg}");
        assert!(
            msg.contains(&(MAX_WASM_SIZE_BYTES + 1).to_string()),
            "Error should contain actual size: {msg}"
        );
    }

    // ── Test 10: submit_message_format ────────────────────────────────────

    #[test]
    fn submit_message_format() {
        let tmp = tempfile::tempdir().unwrap();
        let builder = ToolBuilder::new(tmp.path().to_path_buf()).unwrap();

        let tool = GeneratedTool {
            name: "format_test_tool".to_string(),
            description: "Test".to_string(),
            argument_schema: serde_json::json!({}),
            capabilities: vec!["network".to_string(), "stdout".to_string()],
            wasm_bytes: None,
            source_code: "fn main() {}".to_string(),
            approved: false,
            created_at: "0".to_string(),
        };

        let msg = builder.submit_for_approval(tool);

        assert!(
            msg.contains("format_test_tool"),
            "Message must include tool name: {msg}"
        );
        assert!(
            msg.contains("network"),
            "Message must list capabilities: {msg}"
        );
        assert!(
            msg.contains("approve format_test_tool"),
            "Message must contain approval instruction: {msg}"
        );
    }

    // ── Extra: approved flag set on approval ─────────────────────────────

    #[test]
    fn approved_flag_set_on_approval() {
        let tmp = tempfile::tempdir().unwrap();
        let builder = ToolBuilder::new(tmp.path().to_path_buf()).unwrap();
        let gate = ToolGate::new();

        let tool = GeneratedTool {
            name: "flag_test_tool".to_string(),
            description: "Test approved flag".to_string(),
            argument_schema: serde_json::json!({}),
            capabilities: vec![],
            wasm_bytes: None,
            source_code: "fn main() {}".to_string(),
            approved: false,
            created_at: "0".to_string(),
        };

        assert!(!tool.approved);
        builder.submit_for_approval(tool);
        // After approval, pending list should be empty (tool was removed)
        builder.approve_tool("flag_test_tool", &gate).unwrap();
        assert!(builder.list_pending().is_empty(), "Pending must be empty after approval");
    }

    // ── Extra: duplicate submission deduplicates ──────────────────────────

    #[test]
    fn duplicate_submission_deduplicates() {
        let tmp = tempfile::tempdir().unwrap();
        let builder = ToolBuilder::new(tmp.path().to_path_buf()).unwrap();

        let make_tool = || GeneratedTool {
            name: "dup_tool".to_string(),
            description: "First".to_string(),
            argument_schema: serde_json::json!({}),
            capabilities: vec![],
            wasm_bytes: None,
            source_code: "fn main() {}".to_string(),
            approved: false,
            created_at: "0".to_string(),
        };

        builder.submit_for_approval(make_tool());
        builder.submit_for_approval(make_tool());

        // Should have only one entry in pending (last-writer-wins dedup)
        assert_eq!(
            builder.list_pending().len(),
            1,
            "Duplicate submissions should be deduplicated"
        );
    }

    // ── Extra: capabilities_from_strings conversion ───────────────────────

    #[test]
    fn capabilities_from_strings_maps_known_caps() {
        let input = vec![
            "stdout".to_string(),
            "network".to_string(),
            "filesystem".to_string(),
            "env".to_string(),
            "unknown_cap".to_string(), // should be ignored
        ];
        let caps = capabilities_from_strings(&input);
        assert_eq!(caps.len(), 4, "Unknown caps should be ignored");
        assert!(caps.iter().any(|c| matches!(c, WasmCapability::Stdout)));
        assert!(caps.iter().any(|c| matches!(c, WasmCapability::Network { .. })));
        assert!(caps.iter().any(|c| matches!(c, WasmCapability::Filesystem { .. })));
        assert!(caps.iter().any(|c| matches!(c, WasmCapability::Env { .. })));
    }
}
