#!/usr/bin/env bash
# ironclaw-setup.sh — IronClaw Vault Seeding & Post-Install Setup
#
# Solves the #1 deployment friction: IronClaw's encrypted vault takes priority
# over .env values. After a fresh install or DB wipe, the vault is empty and
# IronClaw can't reach the LLM provider — even though .env has the credentials.
#
# This script seeds the vault non-interactively from environment variables,
# so `docker compose up` just works without a manual `ironclaw onboard` step.
#
# Usage:
#   source /path/to/.env && bash deploy/ironclaw-setup.sh
#   # or via Docker entrypoint (see deploy/README.md)
#
# Required environment variables (at least one LLM config):
#   LLM_API_KEY     — API key for your LLM provider (or LiteLLM master key)
#   LLM_BASE_URL    — Base URL for OpenAI-compatible endpoint (e.g. LiteLLM proxy)
#   LLM_MODEL       — Model name (e.g. claude-sonnet, gpt-4o-mini)
#
# Optional:
#   IRONCLAW_BIN    — Path to ironclaw binary (default: auto-detect)
#   IRONCLAW_DIR    — IronClaw workspace dir (default: ~/.ironclaw)
#   SKIP_WORKSPACE  — Set to 1 to skip workspace file copy
#
# Vault behavior:
#   Layer 1 (this script): env vars → vault (for automated/Docker deploys)
#   Layer 2 (existing):    vault → IronClaw (for interactive installs)
#   Layer 3 (fallback):    onboard wizard (first-run, no vault/env)

set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────

IRONCLAW_BIN="${IRONCLAW_BIN:-}"
IRONCLAW_DIR="${IRONCLAW_DIR:-${HOME}/.ironclaw}"
SKIP_WORKSPACE="${SKIP_WORKSPACE:-0}"

# LLM credentials from environment
LLM_API_KEY="${LLM_API_KEY:-${OPENAI_API_KEY:-${ANTHROPIC_API_KEY:-}}}"
LLM_BASE_URL="${LLM_BASE_URL:-http://localhost:4000/v1}"
LLM_MODEL="${LLM_MODEL:-claude-sonnet}"

# ── Detect IronClaw binary ───────────────────────────────────────────────────

if [ -z "$IRONCLAW_BIN" ]; then
    for candidate in \
        /usr/local/bin/ironclaw \
        /usr/bin/ironclaw \
        "${HOME}/.local/bin/ironclaw" \
        "${HOME}/.cargo/bin/ironclaw"; do
        if [ -x "$candidate" ]; then
            IRONCLAW_BIN="$candidate"
            break
        fi
    done
fi

if [ -z "$IRONCLAW_BIN" ] || [ ! -x "$IRONCLAW_BIN" ]; then
    echo "Error: ironclaw binary not found."
    echo "Install IronClaw first: see https://github.com/nearai/ironclaw"
    exit 1
fi

IRONCLAW_VERSION=$("$IRONCLAW_BIN" --version 2>/dev/null | head -1 || echo "unknown")
echo "IronClaw: $IRONCLAW_BIN ($IRONCLAW_VERSION)"
echo "Workspace: $IRONCLAW_DIR"

# ── Create workspace directory ───────────────────────────────────────────────

mkdir -p "$IRONCLAW_DIR"

# ── Seed vault from environment variables ────────────────────────────────────

if [ -z "$LLM_API_KEY" ]; then
    echo "Warning: LLM_API_KEY not set. Skipping vault seeding."
    echo "  Set LLM_API_KEY (or OPENAI_API_KEY / ANTHROPIC_API_KEY) to auto-configure."
else
    echo "Seeding IronClaw vault from environment..."

    # Try ironclaw config set (if supported by this version)
    if "$IRONCLAW_BIN" config set llm_api_key "$LLM_API_KEY" 2>/dev/null; then
        echo "  ✓ llm_api_key set via ironclaw config"
    else
        # Fallback: write directly to .env (IronClaw reads this before vault on some builds)
        IRONCLAW_ENV="$IRONCLAW_DIR/.env"
        echo "  Writing $IRONCLAW_ENV..."
        {
            echo "# Auto-generated by ironclaw-setup.sh"
            echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            echo ""
            echo "LLM_BACKEND=openai_compatible"
            echo "LLM_BASE_URL=$LLM_BASE_URL"
            echo "LLM_MODEL=$LLM_MODEL"
            echo "ALLOW_HTTP_LLM=true"
            # Only write API key if it's set
            if [ -n "$LLM_API_KEY" ]; then
                echo "LLM_API_KEY=$LLM_API_KEY"
            fi
        } > "$IRONCLAW_ENV"
        chmod 600 "$IRONCLAW_ENV"
        echo "  ✓ $IRONCLAW_ENV written"
    fi

    # Also set base URL and model if config set is supported
    "$IRONCLAW_BIN" config set llm_base_url "$LLM_BASE_URL" 2>/dev/null || true
    "$IRONCLAW_BIN" config set llm_model "$LLM_MODEL" 2>/dev/null || true

    echo "  LLM config: model=$LLM_MODEL base_url=$LLM_BASE_URL"
fi

# ── Copy workspace files (optional) ──────────────────────────────────────────

if [ "$SKIP_WORKSPACE" != "1" ]; then
    WORKSPACE_SRC="${WORKSPACE_DIR:-/opt/lumina-fleet/system/workspace}"
    if [ -d "$WORKSPACE_SRC" ]; then
        echo "Copying workspace files from $WORKSPACE_SRC..."
        cp -n "$WORKSPACE_SRC"/*.md "$IRONCLAW_DIR/" 2>/dev/null || true
        echo "  ✓ Workspace files copied"
    fi
fi

# ── Verify IronClaw can start ─────────────────────────────────────────────────

echo "Verifying IronClaw status..."
if "$IRONCLAW_BIN" status 2>/dev/null | grep -q "LLM configuration"; then
    echo "  ✓ IronClaw status OK"
else
    echo "  ⚠ Could not verify IronClaw status (may be first run)"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "Setup complete. Start IronClaw with:"
echo "  $IRONCLAW_BIN run --no-onboard"
echo ""
echo "If IronClaw still prompts for credentials, run once interactively:"
echo "  $IRONCLAW_BIN onboard --step provider"
