//! EMEM-09: Provenance tracking — "why do you think that?"
//!
//! Every memory tracks its provenance: which conversation it came from, which
//! turn, and what agent or user created it. When a user asks "why do you think
//! that?" or "where did you learn that?", [`ProvenanceTracker::explain_memory`]
//! traces back to the source and returns a human-readable explanation.
//!
//! Privacy invariant: provenance only shows source conversations the requesting
//! user participated in. If a shared memory was created by another user, only the
//! creator's display name is shown — never the full conversation content.

use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};

use crate::error::{LuminaError, Result};
use super::types::{Memory, MemoryType, Visibility, new_uuid, iso_now};

// ── CreatorType ───────────────────────────────────────────────────────────────

/// Who or what created a memory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CreatorType {
    /// Created directly from a user statement during a conversation.
    User,
    /// Generated by Reflexa (the memory consolidation engine).
    Reflexa,
    /// Abstracted by the PrincipleEngine from clusters of Preferences.
    Principle,
}

impl CreatorType {
    pub fn from_str(s: &str) -> Self {
        match s {
            "reflexa" => Self::Reflexa,
            "principle" => Self::Principle,
            _ => Self::User,
        }
    }

    pub fn to_db(&self) -> &'static str {
        match self {
            Self::User => "user",
            Self::Reflexa => "reflexa",
            Self::Principle => "principle",
        }
    }
}

// ── ProvenanceRecord ──────────────────────────────────────────────────────────

/// Provenance metadata for a single memory.
///
/// Stored alongside the memory; surfaced on "why do you think" queries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceRecord {
    /// The memory this record describes.
    pub memory_id: String,
    /// Which conversation produced this memory (matches memories_v2.source_conversation_id).
    pub source_conversation_id: Option<String>,
    /// Which turn within the conversation (matches memories_v2.source_turn_index).
    pub source_turn_index: Option<i32>,
    /// Confidence at time of creation (0.0–1.0).
    pub confidence: f32,
    /// ISO 8601 timestamp when this provenance record was created.
    pub created_at: String,
    /// Who or what created the memory.
    pub creator_type: CreatorType,
    /// User ID of the creator (may differ from the memory owner for shared memories).
    pub creator_user_id: String,
}

impl ProvenanceRecord {
    pub fn new(
        memory_id: impl Into<String>,
        source_conversation_id: Option<String>,
        source_turn_index: Option<i32>,
        confidence: f32,
        creator_type: CreatorType,
        creator_user_id: impl Into<String>,
    ) -> Self {
        Self {
            memory_id: memory_id.into(),
            source_conversation_id,
            source_turn_index,
            confidence,
            created_at: iso_now(),
            creator_type,
            creator_user_id: creator_user_id.into(),
        }
    }
}

// ── ProvenanceTracker ─────────────────────────────────────────────────────────

/// Provides "why do you think that?" explanations for memories.
///
/// Works with the `memories_v2` table via a raw `&Connection`. Does not hold
/// a store reference so it can be passed freely without lifetime conflicts.
pub struct ProvenanceTracker;

impl ProvenanceTracker {
    /// Explain the provenance of a memory to a requesting user.
    ///
    /// Returns a human-readable string describing where the memory came from.
    ///
    /// Privacy: if the memory was created by a different user (shared memory),
    /// the response shows the creator's display name but NOT the source conversation.
    pub fn explain_memory(
        conn: &Connection,
        memory_id: &str,
        requesting_user_id: &str,
    ) -> Result<String> {
        // Load the memory — check both owned and shared memories.
        let memory = Self::load_memory_any_visibility(conn, memory_id)?
            .ok_or_else(|| LuminaError::Config(
                "I don't have that information in my memory.".to_string()
            ))?;

        // Privacy check for shared memories created by another user.
        if memory.visibility == Visibility::Shared && memory.user_id != requesting_user_id {
            return Ok(Self::format_shared_explanation(&memory));
        }

        // Owned or system memory — retrieve full provenance.
        let creator_type = Self::infer_creator_type(&memory);
        let confidence_note = if memory.confidence < 0.6 {
            format!(
                " I'm only moderately confident about this (confidence: {:.2}). \
                 It was extracted from a conversation where the topic may have been ambiguous.",
                memory.confidence
            )
        } else {
            String::new()
        };

        match creator_type {
            CreatorType::Reflexa => {
                // Consolidated memory — look up source memories.
                let source_count = Self::count_reflexa_sources(conn, memory_id);
                let dates = Self::reflexa_source_dates(conn, memory_id);
                let date_phrase = if dates.is_empty() {
                    "previous conversations".to_string()
                } else {
                    format!("conversations on {}", dates.join(", "))
                };
                Ok(format!(
                    "This is a consolidated memory, combining {source_count} related \
                     fact(s) from {date_phrase}.{confidence_note}"
                ))
            }

            CreatorType::Principle => {
                // Principle abstracted from Preference memories.
                let pref_count = Self::count_principle_sources(conn, memory_id);
                let tags_summary = memory.tags.join(", ");
                let tag_note = if tags_summary.is_empty() {
                    String::new()
                } else {
                    format!(" Related themes: {tags_summary}.")
                };
                Ok(format!(
                    "This pattern was abstracted from {pref_count} preference(s) \
                     I observed over time.{tag_note}{confidence_note}"
                ))
            }

            CreatorType::User => {
                // Direct user statement — look up source conversation.
                match &memory.source_conversation_id {
                    None => {
                        if memory.created_at.starts_with("1970") || memory.created_at.is_empty() {
                            Ok(format!(
                                "This is an early memory from before detailed tracking. \
                                 I'm not sure exactly when I learned it.{confidence_note}"
                            ))
                        } else {
                            Ok(format!(
                                "This memory was learned from a previous conversation \
                                 that's no longer available.{confidence_note}"
                            ))
                        }
                    }
                    Some(conv_id) => {
                        let date = Self::extract_date(&memory.created_at);
                        let turn_note = match memory.source_turn_index {
                            Some(t) => format!(" (turn {t})"),
                            None => String::new(),
                        };
                        let excerpt = Self::fetch_turn_excerpt(conn, conv_id, memory.source_turn_index);
                        match excerpt {
                            Some(ex) => Ok(format!(
                                "I learned this from our conversation on {date}{turn_note}. \
                                 You said: '{ex}' and I extracted: '{content}'.{confidence_note}",
                                content = memory.content
                            )),
                            None => Ok(format!(
                                "I learned this from our conversation on {date}{turn_note}. \
                                 The original exchange is no longer available, but I extracted: \
                                 '{content}'.{confidence_note}",
                                content = memory.content
                            )),
                        }
                    }
                }
            }
        }
    }

    /// Return the raw provenance chain for a memory.
    ///
    /// Provides all available provenance fields for programmatic inspection.
    /// Callers needing human-readable text should use [`explain_memory`] instead.
    pub fn trace_source(conn: &Connection, memory_id: &str) -> Result<Option<ProvenanceRecord>> {
        let mut stmt = conn.prepare(
            "SELECT id, source_conversation_id, source_turn_index, confidence,
                    created_at, memory_type, user_id
             FROM memories_v2 WHERE id = ?1"
        ).map_err(|e| LuminaError::Config(format!("trace_source prepare: {e}")))?;

        let result = stmt.query_row(params![memory_id], |row| {
            let mem_type: String = row.get(5)?;
            let user_id: String = row.get(6)?;
            let creator_type = if mem_type == "principle" {
                CreatorType::Principle
            } else {
                // Check if there is a reflexa tag — no DB field yet, use heuristic.
                CreatorType::User
            };
            Ok(ProvenanceRecord {
                memory_id: row.get(0)?,
                source_conversation_id: row.get(1)?,
                source_turn_index: row.get(2)?,
                confidence: row.get(3).unwrap_or(0.8),
                created_at: row.get(4).unwrap_or_default(),
                creator_type,
                creator_user_id: user_id,
            })
        }).ok();

        Ok(result)
    }

    /// Supersede an existing memory with a user correction.
    ///
    /// Sets the old memory's `superseded_by` to the new correction memory's ID,
    /// and sets the correction's confidence to 1.0 (user-corrected is authoritative).
    pub fn correct_memory(
        conn: &Connection,
        old_memory_id: &str,
        corrected_content: impl Into<String>,
        correcting_user_id: &str,
    ) -> Result<Memory> {
        // Load old memory to inherit type/sensitivity/visibility.
        let old = Self::load_memory_any_visibility(conn, old_memory_id)?
            .ok_or_else(|| LuminaError::Config(format!("memory {old_memory_id} not found")))?;

        let new_id = new_uuid();
        let now = iso_now();
        let content: String = corrected_content.into();

        // Insert the correction with confidence = 1.0 (user-corrected).
        conn.execute(
            "INSERT INTO memories_v2
             (id, user_id, memory_type, visibility, sensitivity, content, embedding,
              source_conversation_id, source_turn_index, confidence, access_count,
              last_accessed, created_at, updated_at, superseded_by, tags)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, NULL, NULL, NULL, 1.0, 0, NULL, ?7, ?7, NULL, '[]')",
            params![
                new_id,
                correcting_user_id,
                old.memory_type.to_db(),
                old.visibility.to_db(),
                old.sensitivity.to_db(),
                content,
                now,
            ],
        ).map_err(|e| LuminaError::Config(format!("correct_memory insert: {e}")))?;

        // Mark old memory as superseded.
        conn.execute(
            "UPDATE memories_v2 SET superseded_by = ?1, updated_at = ?2 WHERE id = ?3",
            params![new_id, now, old_memory_id],
        ).map_err(|e| LuminaError::Config(format!("correct_memory supersede: {e}")))?;

        Ok(Memory {
            id: new_id,
            user_id: correcting_user_id.to_string(),
            memory_type: old.memory_type,
            visibility: old.visibility,
            sensitivity: old.sensitivity,
            content,
            embedding: Vec::new(),
            source_conversation_id: None,
            source_turn_index: None,
            confidence: 1.0,
            access_count: 0,
            last_accessed: None,
            created_at: now.clone(),
            updated_at: now,
            superseded_by: None,
            tags: Vec::new(),
        })
    }

    /// Detect whether a piece of user text is asking for memory provenance.
    ///
    /// Pure keyword lookup — no LLM required (per inference de-bloat rules).
    pub fn is_provenance_query(text: &str) -> bool {
        let lower = text.to_lowercase();
        let phrases: &[&str] = &[
            "why do you think",
            "where did you learn",
            "how do you know",
            "why do you believe",
            "where did that come from",
            "how did you learn",
            "why do you say",
            "what makes you think",
            "where does that come from",
            "did i tell you",
            "where did you get that",
            "how do you know that",
        ];
        phrases.iter().any(|phrase| lower.contains(phrase))
    }
}

// ── Private helpers ────────────────────────────────────────────────────────────

impl ProvenanceTracker {
    /// Load a memory by ID without user-scoping (needed for cross-user shared lookup).
    fn load_memory_any_visibility(conn: &Connection, memory_id: &str) -> Result<Option<Memory>> {
        let mut stmt = conn.prepare(
            "SELECT id, user_id, memory_type, visibility, sensitivity, content, embedding,
                    source_conversation_id, source_turn_index, confidence, access_count,
                    last_accessed, created_at, updated_at, superseded_by, tags
             FROM memories_v2 WHERE id = ?1"
        ).map_err(|e| LuminaError::Config(format!("load_memory_any_visibility prepare: {e}")))?;

        let mut rows = stmt.query_map(params![memory_id], super::row_to_memory)
            .map_err(|e| LuminaError::Config(format!("load_memory_any_visibility query: {e}")))?;

        match rows.next() {
            Some(Ok(m)) => Ok(Some(m)),
            Some(Err(e)) => Err(LuminaError::Config(format!("load_memory_any_visibility row: {e}"))),
            None => Ok(None),
        }
    }

    /// Infer the creator type from the memory fields (no separate provenance table needed).
    fn infer_creator_type(memory: &Memory) -> CreatorType {
        match memory.memory_type {
            MemoryType::Principle => CreatorType::Principle,
            _ => {
                // Check if the memory has the "reflexa" tag (set by consolidation engine).
                if memory.tags.iter().any(|t| t == "reflexa" || t == "consolidated") {
                    CreatorType::Reflexa
                } else {
                    CreatorType::User
                }
            }
        }
    }

    /// Format a privacy-safe explanation for a shared memory from another user.
    fn format_shared_explanation(memory: &Memory) -> String {
        let date = Self::extract_date(&memory.created_at);
        format!(
            "This was shared by {} on {}.",
            memory.user_id, date
        )
    }

    /// Extract the date portion (YYYY-MM-DD) from an ISO 8601 timestamp.
    fn extract_date(iso: &str) -> &str {
        iso.get(..10).unwrap_or(iso)
    }

    /// Try to fetch the user message excerpt from a conversation turn.
    ///
    /// Attempts to read from a `conversation_turns` table if it exists; returns
    /// `None` gracefully if the table or turn is missing (no hard dependency).
    fn fetch_turn_excerpt(
        conn: &Connection,
        conversation_id: &str,
        turn_index: Option<i32>,
    ) -> Option<String> {
        let turn_idx = turn_index?;
        // Try to fetch from conversation_turns table — not required to exist.
        let result: rusqlite::Result<String> = conn.query_row(
            "SELECT content FROM conversation_turns
             WHERE conversation_id = ?1 AND turn_index = ?2 AND role = 'user'
             LIMIT 1",
            params![conversation_id, turn_idx],
            |r| r.get(0),
        );
        match result {
            Ok(content) => {
                // Truncate long excerpts to 120 chars with ellipsis.
                if content.len() > 120 {
                    Some(format!("{}…", &content[..120]))
                } else {
                    Some(content)
                }
            }
            Err(_) => None,
        }
    }

    /// Count the number of source memories that were consolidated into a Reflexa memory.
    ///
    /// Falls back to 2 (a reasonable minimum) if no tracking table is available.
    fn count_reflexa_sources(conn: &Connection, memory_id: &str) -> usize {
        let result: rusqlite::Result<i64> = conn.query_row(
            "SELECT COUNT(*) FROM reflexa_sources WHERE consolidated_memory_id = ?1",
            params![memory_id],
            |r| r.get(0),
        );
        result.unwrap_or(2) as usize
    }

    /// Fetch the creation dates of Reflexa source memories.
    fn reflexa_source_dates(conn: &Connection, memory_id: &str) -> Vec<String> {
        let mut stmt = match conn.prepare(
            "SELECT m.created_at FROM reflexa_sources rs
             JOIN memories_v2 m ON m.id = rs.source_memory_id
             WHERE rs.consolidated_memory_id = ?1
             ORDER BY m.created_at ASC"
        ) {
            Ok(s) => s,
            Err(_) => return Vec::new(),
        };

        let rows = match stmt.query_map(params![memory_id], |r| r.get::<_, String>(0)) {
            Ok(r) => r,
            Err(_) => return Vec::new(),
        };

        rows.filter_map(|r| r.ok())
            .map(|ts| ts.get(..10).unwrap_or(&ts).to_string())
            .collect()
    }

    /// Count the number of Preference memories that gave rise to a Principle.
    ///
    /// Falls back to 5 (the minimum cluster size) if no tracking table is available.
    fn count_principle_sources(conn: &Connection, memory_id: &str) -> usize {
        let result: rusqlite::Result<i64> = conn.query_row(
            "SELECT COUNT(*) FROM principle_sources WHERE principle_memory_id = ?1",
            params![memory_id],
            |r| r.get(0),
        );
        result.unwrap_or(5) as usize
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engram::{EngramStore, types::{Memory, MemoryType, SensitivityCategory, Visibility, new_uuid, iso_now}};
    use rusqlite::params;

    fn test_key() -> Vec<u8> { vec![0u8; 32] }

    fn tmp_db(tag: &str) -> std::path::PathBuf {
        let p = std::path::PathBuf::from(format!("/tmp/lumina_prov_test_{tag}.db"));
        let _ = std::fs::remove_file(&p);
        p
    }

    fn open_store(tag: &str) -> (EngramStore, std::path::PathBuf) {
        let path = tmp_db(tag);
        let store = EngramStore::open(&path, &test_key()).unwrap();
        (store, path)
    }

    // ── test_explain_memory_traces_source ─────────────────────────────────────

    #[test]
    fn test_explain_memory_traces_source() {
        let (store, path) = open_store("explain_source");

        // Insert a memory with a known source conversation.
        let mut mem = Memory::new("user-alice", MemoryType::Semantic, SensitivityCategory::General, "likes dark roast coffee");
        mem.source_conversation_id = Some("conv-001".to_string());
        mem.source_turn_index = Some(3);
        mem.confidence = 0.85;
        store.insert_memory(&mem).unwrap();

        let explanation = ProvenanceTracker::explain_memory(
            &store.conn, &mem.id, "user-alice"
        ).unwrap();

        // Should mention "conversation" and the content.
        assert!(
            explanation.contains("conversation") || explanation.contains("learned"),
            "Explanation should mention where it was learned: {explanation}"
        );

        let _ = std::fs::remove_file(&path);
    }

    // ── test_consolidated_memory_explains_sources ─────────────────────────────

    #[test]
    fn test_consolidated_memory_explains_sources() {
        let (store, path) = open_store("consolidated");

        // Insert a Semantic memory tagged "reflexa" (simulates consolidation).
        let mut mem = Memory::new("user-bob", MemoryType::Semantic, SensitivityCategory::General, "consistently prefers late hours");
        mem.tags = vec!["reflexa".to_string(), "consolidated".to_string()];
        store.insert_memory(&mem).unwrap();

        let explanation = ProvenanceTracker::explain_memory(
            &store.conn, &mem.id, "user-bob"
        ).unwrap();

        assert!(
            explanation.contains("consolidated memory") || explanation.contains("combining"),
            "Reflexa memory should explain consolidation: {explanation}"
        );

        let _ = std::fs::remove_file(&path);
    }

    // ── test_principle_memory_explains_sources ────────────────────────────────

    #[test]
    fn test_principle_memory_explains_sources() {
        let (store, path) = open_store("principle");

        // Insert a Principle memory.
        let mut mem = Memory::new("user-carol", MemoryType::Principle, SensitivityCategory::General, "strongly values efficiency and dislikes redundancy");
        mem.tags = vec!["work".to_string(), "efficiency".to_string()];
        store.insert_memory(&mem).unwrap();

        let explanation = ProvenanceTracker::explain_memory(
            &store.conn, &mem.id, "user-carol"
        ).unwrap();

        assert!(
            explanation.contains("pattern") || explanation.contains("abstracted") || explanation.contains("preference"),
            "Principle memory should explain abstraction: {explanation}"
        );

        let _ = std::fs::remove_file(&path);
    }

    // ── test_low_confidence_disclosed ─────────────────────────────────────────

    #[test]
    fn test_low_confidence_disclosed() {
        let (store, path) = open_store("low_confidence");

        let mut mem = Memory::new("user-dave", MemoryType::Semantic, SensitivityCategory::General, "might prefer mornings");
        mem.confidence = 0.45; // Below 0.6 threshold.
        mem.source_conversation_id = Some("conv-low".to_string());
        store.insert_memory(&mem).unwrap();

        let explanation = ProvenanceTracker::explain_memory(
            &store.conn, &mem.id, "user-dave"
        ).unwrap();

        assert!(
            explanation.contains("confidence") || explanation.contains("moderately"),
            "Low-confidence memory should disclose uncertainty: {explanation}"
        );
        assert!(
            explanation.contains("0.45") || explanation.contains("moderate"),
            "Should include confidence value: {explanation}"
        );

        let _ = std::fs::remove_file(&path);
    }

    // ── test_correction_supersedes_old_memory ─────────────────────────────────

    #[test]
    fn test_correction_supersedes_old_memory() {
        let (store, path) = open_store("correction");

        // Insert original memory.
        let mut mem = Memory::new("user-eve", MemoryType::Preference, SensitivityCategory::General, "prefers mornings");
        mem.confidence = 0.75;
        store.insert_memory(&mem).unwrap();

        // Apply correction.
        let corrected = ProvenanceTracker::correct_memory(
            &store.conn,
            &mem.id,
            "actually prefers evenings",
            "user-eve",
        ).unwrap();

        // New memory should have confidence 1.0.
        assert_eq!(corrected.confidence, 1.0, "User correction should have confidence 1.0");
        assert_eq!(corrected.content, "actually prefers evenings");

        // Old memory should be superseded.
        let old: String = store.conn.query_row(
            "SELECT superseded_by FROM memories_v2 WHERE id = ?1",
            params![mem.id],
            |r| r.get(0),
        ).unwrap();
        assert_eq!(old, corrected.id, "Old memory should point to correction");

        // New memory should not be superseded.
        let new_superseded: Option<String> = store.conn.query_row(
            "SELECT superseded_by FROM memories_v2 WHERE id = ?1",
            params![corrected.id],
            |r| r.get(0),
        ).unwrap_or(None);
        assert!(new_superseded.is_none(), "Correction should not be superseded");

        let _ = std::fs::remove_file(&path);
    }

    // ── test_privacy_shared_memory_shows_creator_not_conversation ─────────────

    #[test]
    fn test_privacy_shared_memory_shows_creator_not_conversation() {
        let (store, path) = open_store("privacy_shared");

        // Insert a shared memory created by "user-frank".
        let mut mem = Memory::new("user-frank", MemoryType::Semantic, SensitivityCategory::Household, "family dinner is Fridays");
        mem.visibility = Visibility::Shared;
        mem.source_conversation_id = Some("conv-frank-private-001".to_string());
        store.insert_memory(&mem).unwrap();

        // "user-grace" requests explanation of this shared memory.
        let explanation = ProvenanceTracker::explain_memory(
            &store.conn, &mem.id, "user-grace"
        ).unwrap();

        // Should show creator name, NOT the conversation ID.
        assert!(
            explanation.contains("user-frank"),
            "Shared memory explanation should identify the creator: {explanation}"
        );
        assert!(
            !explanation.contains("conv-frank-private-001"),
            "Shared memory explanation must NOT reveal the source conversation: {explanation}"
        );

        let _ = std::fs::remove_file(&path);
    }

    // ── test_is_provenance_query_detection ────────────────────────────────────

    #[test]
    fn test_is_provenance_query_detection() {
        // Should detect provenance queries.
        let provenance_queries = [
            "Why do you think I prefer mornings?",
            "where did you learn that about me",
            "How do you know I like dark roast?",
            "Why do you believe I dislike meetings?",
            "where did that come from?",
            "How did you learn that?",
            "Why do you say I'm a morning person?",
            "What makes you think I prefer evenings?",
            "Did I tell you about my coffee preference?",
            "Where did you get that information?",
        ];
        for query in &provenance_queries {
            assert!(
                ProvenanceTracker::is_provenance_query(query),
                "Should detect provenance query: {query}"
            );
        }

        // Should NOT detect these as provenance queries.
        let non_provenance = [
            "What's the weather today?",
            "Schedule a meeting for Friday",
            "I prefer dark mode",
            "Can you help me write an email?",
            "Tell me about quantum computing",
        ];
        for query in &non_provenance {
            assert!(
                !ProvenanceTracker::is_provenance_query(query),
                "Should NOT detect as provenance query: {query}"
            );
        }
    }

    // ── test_missing_source_conversation ─────────────────────────────────────

    #[test]
    fn test_missing_source_conversation_handled_gracefully() {
        let (store, path) = open_store("missing_conv");

        // Memory with no source_conversation_id.
        let mem = Memory::new("user-helen", MemoryType::Semantic, SensitivityCategory::General, "an early memory");
        store.insert_memory(&mem).unwrap();

        let explanation = ProvenanceTracker::explain_memory(
            &store.conn, &mem.id, "user-helen"
        ).unwrap();

        // Should gracefully handle missing conversation.
        assert!(
            explanation.contains("no longer available") || explanation.contains("not sure") || explanation.contains("tracking"),
            "Missing conversation should be handled gracefully: {explanation}"
        );

        let _ = std::fs::remove_file(&path);
    }

    // ── test_trace_source_returns_record ─────────────────────────────────────

    #[test]
    fn test_trace_source_returns_record() {
        let (store, path) = open_store("trace_source");

        let mut mem = Memory::new("user-ivan", MemoryType::Preference, SensitivityCategory::General, "prefers concise reports");
        mem.source_conversation_id = Some("conv-456".to_string());
        mem.source_turn_index = Some(7);
        mem.confidence = 0.9;
        store.insert_memory(&mem).unwrap();

        let record = ProvenanceTracker::trace_source(&store.conn, &mem.id).unwrap();
        assert!(record.is_some(), "trace_source should return a record");
        let record = record.unwrap();
        assert_eq!(record.memory_id, mem.id);
        assert_eq!(record.source_conversation_id.as_deref(), Some("conv-456"));
        assert_eq!(record.source_turn_index, Some(7));
        assert!((record.confidence - 0.9).abs() < 1e-5);

        let _ = std::fs::remove_file(&path);
    }

    // ── test_nonexistent_memory ────────────────────────────────────────────────

    #[test]
    fn test_nonexistent_memory_returns_error() {
        let (store, path) = open_store("nonexistent");

        let result = ProvenanceTracker::explain_memory(
            &store.conn, "memory-does-not-exist", "user-alice"
        );

        assert!(result.is_err(), "Non-existent memory should return an error");

        let _ = std::fs::remove_file(&path);
    }

    // ── test_creator_type_round_trip ─────────────────────────────────────────

    #[test]
    fn test_creator_type_round_trip() {
        assert_eq!(CreatorType::from_str("user"), CreatorType::User);
        assert_eq!(CreatorType::from_str("reflexa"), CreatorType::Reflexa);
        assert_eq!(CreatorType::from_str("principle"), CreatorType::Principle);
        assert_eq!(CreatorType::from_str("unknown"), CreatorType::User); // fallback

        assert_eq!(CreatorType::User.to_db(), "user");
        assert_eq!(CreatorType::Reflexa.to_db(), "reflexa");
        assert_eq!(CreatorType::Principle.to_db(), "principle");
    }
}
