//! EMEM-01: Memory type taxonomy for Engram v2.
//!
//! Defines the type system for the memories_v2 schema: MemoryType, Visibility,
//! SensitivityCategory, and the Memory struct. This is the foundation for all
//! subsequent Engram v2 work.

use serde::{Deserialize, Serialize};

// ── MemoryType ────────────────────────────────────────────────────────────────

/// The cognitive category of a memory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MemoryType {
    /// What happened: events, activities, conversations, experiences.
    /// Created from conversations; decays over time; consolidated into Semantic.
    Episodic,
    /// Facts, knowledge, stable information about the world or the user.
    /// Extracted from Episodic; updated on contradiction; long-lived.
    Semantic,
    /// Likes, dislikes, style choices, recurring preferences.
    /// Extracted from conversations; refined over time.
    Preference,
    /// Abstracted patterns from clusters of Preferences (EMEM-05).
    /// Generated by the PrincipleEngine; highest retrieval priority.
    Principle,
}

impl MemoryType {
    /// Parse from the string stored in the database.
    pub fn from_db(s: &str) -> Self {
        match s {
            "episodic" => Self::Episodic,
            "preference" => Self::Preference,
            "principle" => Self::Principle,
            _ => Self::Semantic, // "semantic" + unknown defaults to Semantic
        }
    }

    /// Canonical string for database storage.
    pub fn to_db(&self) -> &'static str {
        match self {
            Self::Episodic => "episodic",
            Self::Semantic => "semantic",
            Self::Preference => "preference",
            Self::Principle => "principle",
        }
    }

    /// Retrieval priority — lower = higher priority in context injection.
    /// Principle (0) > Preference (1) > Semantic (2) > Episodic (3).
    pub fn retrieval_priority(&self) -> u8 {
        match self {
            Self::Principle => 0,
            Self::Preference => 1,
            Self::Semantic => 2,
            Self::Episodic => 3,
        }
    }
}

// ── Visibility ────────────────────────────────────────────────────────────────

/// Who can see a memory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Visibility {
    /// Only the owning user can see this memory. Default for all new memories.
    Private,
    /// All household members can see this memory. Requires explicit share action.
    Shared,
    /// All users can see this. Only written by admin/system processes.
    System,
}

impl Visibility {
    pub fn from_db(s: &str) -> Self {
        match s {
            "shared" => Self::Shared,
            "system" => Self::System,
            _ => Self::Private, // "private" + unknown defaults to Private (fail-safe)
        }
    }

    pub fn to_db(&self) -> &'static str {
        match self {
            Self::Private => "private",
            Self::Shared => "shared",
            Self::System => "system",
        }
    }
}

// ── SensitivityCategory ───────────────────────────────────────────────────────

/// The sensitivity of memory content. Controls forced visibility and share permissions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SensitivityCategory {
    /// Medical conditions, medications, symptoms, health data. ALWAYS Private.
    Health,
    /// Bank accounts, income, debts, financial data. ALWAYS Private.
    Finance,
    /// Relationships, private opinions, personal struggles. ALWAYS Private.
    Personal,
    /// Job tasks, career decisions. Private by default, can be shared.
    Work,
    /// Shared events, grocery lists, family schedule. Shared by default.
    Household,
    /// General facts, preferences, world knowledge. Private by default.
    General,
    /// Infrastructure facts, tool catalog. System visibility.
    System,
}

impl SensitivityCategory {
    pub fn from_db(s: &str) -> Self {
        match s {
            "health" => Self::Health,
            "finance" => Self::Finance,
            "personal" => Self::Personal,
            "work" => Self::Work,
            "household" => Self::Household,
            "system" => Self::System,
            _ => Self::General,
        }
    }

    pub fn to_db(&self) -> &'static str {
        match self {
            Self::Health => "health",
            Self::Finance => "finance",
            Self::Personal => "personal",
            Self::Work => "work",
            Self::Household => "household",
            Self::General => "general",
            Self::System => "system",
        }
    }

    /// Whether this category must ALWAYS be private — cannot be shared under any circumstances.
    pub fn is_always_private(&self) -> bool {
        matches!(self, Self::Health | Self::Finance | Self::Personal)
    }

    /// The default visibility for a new memory of this sensitivity.
    pub fn default_visibility(&self) -> Visibility {
        match self {
            Self::Health | Self::Finance | Self::Personal | Self::Work | Self::General => {
                Visibility::Private
            }
            Self::Household => Visibility::Shared,
            Self::System => Visibility::System,
        }
    }
}

// ── Memory ────────────────────────────────────────────────────────────────────

/// A typed, provenanced memory in Engram v2.
///
/// Stored in the `memories_v2` table (SQLCipher encrypted). All fields have
/// database-level representations as TEXT or BLOB or INTEGER.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Memory {
    /// UUID primary key.
    pub id: String,
    /// Owner. Every query MUST filter by this field.
    pub user_id: String,
    /// Cognitive category.
    pub memory_type: MemoryType,
    /// Access control level.
    pub visibility: Visibility,
    /// Content sensitivity for auto-privacy enforcement.
    pub sensitivity: SensitivityCategory,
    /// The actual remembered content.
    pub content: String,
    /// L2-normalized f32 embedding for cosine similarity search.
    /// May be empty if embedding generation was unavailable at ingest time.
    pub embedding: Vec<f32>,
    /// Which conversation produced this memory (provenance).
    pub source_conversation_id: Option<String>,
    /// Which turn within the conversation (provenance).
    pub source_turn_index: Option<i32>,
    /// Confidence 0.0–1.0. Direct operator statements = 1.0. LLM-extracted = 0.6–0.9.
    pub confidence: f32,
    /// Number of times this memory was retrieved.
    pub access_count: i32,
    /// ISO 8601 timestamp of the last retrieval.
    pub last_accessed: Option<String>,
    /// ISO 8601 timestamp of creation.
    pub created_at: String,
    /// ISO 8601 timestamp of last update.
    pub updated_at: String,
    /// If this memory was superseded by a newer version, this is the newer memory's ID.
    pub superseded_by: Option<String>,
    /// Free-form tags (stored as JSON array string in DB).
    pub tags: Vec<String>,
}

impl Memory {
    /// Create a new memory with sensible defaults.
    pub fn new(
        user_id: impl Into<String>,
        memory_type: MemoryType,
        sensitivity: SensitivityCategory,
        content: impl Into<String>,
    ) -> Self {
        let now = iso_now();
        let visibility = sensitivity.default_visibility();
        Self {
            id: new_uuid(),
            user_id: user_id.into(),
            memory_type,
            visibility,
            sensitivity,
            content: content.into(),
            embedding: Vec::new(),
            source_conversation_id: None,
            source_turn_index: None,
            confidence: 0.8,
            access_count: 0,
            last_accessed: None,
            created_at: now.clone(),
            updated_at: now,
            superseded_by: None,
            tags: Vec::new(),
        }
    }

    /// Display label for LLM context injection (EMEM-07).
    pub fn type_label(&self) -> &'static str {
        match self.memory_type {
            MemoryType::Principle => "[Principle]",
            MemoryType::Preference => "[Preference]",
            MemoryType::Semantic => "[Fact]",
            MemoryType::Episodic => "[Recent]",
        }
    }
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Generate a new UUID v4 string.
pub fn new_uuid() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// Return the current time as an ISO 8601 string (seconds precision).
pub fn iso_now() -> String {
    // Use SystemTime for a portable, no-chrono implementation.
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    // Format as YYYY-MM-DDTHH:MM:SSZ from Unix timestamp.
    unix_secs_to_iso(secs)
}

/// Convert a Unix timestamp (seconds) to ISO 8601 date-time string.
/// Minimal implementation — avoids chrono dependency.
pub fn unix_secs_to_iso(secs: u64) -> String {
    // Days since epoch
    let days = secs / 86400;
    let time = secs % 86400;
    let h = time / 3600;
    let m = (time % 3600) / 60;
    let s = time % 60;

    // Gregorian calendar from day number (Fliegel-Van Flandern algorithm)
    let jd = days + 2440588; // Julian Day Number for 1970-01-01
    let l = jd + 68569;
    let n = (4 * l) / 146097;
    let l = l - (146097 * n + 3) / 4;
    let year = 4000 * (l + 1) / 1461001;
    let l = l - 1461 * year / 4 + 31;
    let month = 80 * l / 2447;
    let day = l - 2447 * month / 80;
    let l = month / 11;
    let month = month + 2 - 12 * l;
    let year = 100 * (n - 49) + year + l;

    format!("{year:04}-{month:02}-{day:02}T{h:02}:{m:02}:{s:02}Z")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_memory_type_round_trip() {
        for (input, expected) in [
            ("episodic", MemoryType::Episodic),
            ("semantic", MemoryType::Semantic),
            ("preference", MemoryType::Preference),
            ("principle", MemoryType::Principle),
            ("unknown", MemoryType::Semantic), // unknown → Semantic
        ] {
            let t = MemoryType::from_db(input);
            assert_eq!(t, expected, "from_db({input}) mismatch");
        }

        assert_eq!(MemoryType::Episodic.to_db(), "episodic");
        assert_eq!(MemoryType::Semantic.to_db(), "semantic");
        assert_eq!(MemoryType::Preference.to_db(), "preference");
        assert_eq!(MemoryType::Principle.to_db(), "principle");
    }

    #[test]
    fn test_visibility_round_trip() {
        assert_eq!(Visibility::from_db("private"), Visibility::Private);
        assert_eq!(Visibility::from_db("shared"), Visibility::Shared);
        assert_eq!(Visibility::from_db("system"), Visibility::System);
        assert_eq!(Visibility::from_db("bogus"), Visibility::Private); // fail-safe

        assert_eq!(Visibility::Private.to_db(), "private");
        assert_eq!(Visibility::Shared.to_db(), "shared");
        assert_eq!(Visibility::System.to_db(), "system");
    }

    #[test]
    fn test_sensitivity_round_trip() {
        for (input, expected) in [
            ("health", SensitivityCategory::Health),
            ("finance", SensitivityCategory::Finance),
            ("personal", SensitivityCategory::Personal),
            ("work", SensitivityCategory::Work),
            ("household", SensitivityCategory::Household),
            ("general", SensitivityCategory::General),
            ("system", SensitivityCategory::System),
            ("unknown", SensitivityCategory::General),
        ] {
            let t = SensitivityCategory::from_db(input);
            assert_eq!(t, expected, "from_db({input}) mismatch");
            if expected != SensitivityCategory::General || input == "general" {
                // Don't check to_db for the "unknown" case
            }
        }
        assert_eq!(SensitivityCategory::Health.to_db(), "health");
        assert_eq!(SensitivityCategory::Finance.to_db(), "finance");
        assert_eq!(SensitivityCategory::Personal.to_db(), "personal");
    }

    #[test]
    fn test_sensitive_categories_are_always_private() {
        assert!(SensitivityCategory::Health.is_always_private());
        assert!(SensitivityCategory::Finance.is_always_private());
        assert!(SensitivityCategory::Personal.is_always_private());
        assert!(!SensitivityCategory::Work.is_always_private());
        assert!(!SensitivityCategory::Household.is_always_private());
        assert!(!SensitivityCategory::General.is_always_private());
    }

    #[test]
    fn test_sensitivity_default_visibility() {
        assert_eq!(SensitivityCategory::Health.default_visibility(), Visibility::Private);
        assert_eq!(SensitivityCategory::Finance.default_visibility(), Visibility::Private);
        assert_eq!(SensitivityCategory::Personal.default_visibility(), Visibility::Private);
        assert_eq!(SensitivityCategory::Work.default_visibility(), Visibility::Private);
        assert_eq!(SensitivityCategory::General.default_visibility(), Visibility::Private);
        assert_eq!(SensitivityCategory::Household.default_visibility(), Visibility::Shared);
        assert_eq!(SensitivityCategory::System.default_visibility(), Visibility::System);
    }

    #[test]
    fn test_memory_type_retrieval_priority() {
        assert!(MemoryType::Principle.retrieval_priority() < MemoryType::Preference.retrieval_priority());
        assert!(MemoryType::Preference.retrieval_priority() < MemoryType::Semantic.retrieval_priority());
        assert!(MemoryType::Semantic.retrieval_priority() < MemoryType::Episodic.retrieval_priority());
    }

    #[test]
    fn test_memory_new_defaults() {
        let m = Memory::new("user-alice", MemoryType::Preference, SensitivityCategory::General, "likes coffee");
        assert!(!m.id.is_empty(), "UUID should be non-empty");
        assert_eq!(m.user_id, "user-alice");
        assert_eq!(m.memory_type, MemoryType::Preference);
        assert_eq!(m.visibility, Visibility::Private); // General default
        assert_eq!(m.sensitivity, SensitivityCategory::General);
        assert_eq!(m.content, "likes coffee");
        assert_eq!(m.confidence, 0.8);
        assert_eq!(m.access_count, 0);
        assert!(m.source_conversation_id.is_none());
        assert!(m.superseded_by.is_none());
        assert!(m.tags.is_empty());
    }

    #[test]
    fn test_household_memory_defaults_to_shared() {
        let m = Memory::new("user-alice", MemoryType::Semantic, SensitivityCategory::Household, "grocery list: eggs");
        assert_eq!(m.visibility, Visibility::Shared);
    }

    #[test]
    fn test_health_memory_defaults_to_private() {
        let m = Memory::new("user-alice", MemoryType::Semantic, SensitivityCategory::Health, "has allergy");
        assert_eq!(m.visibility, Visibility::Private);
    }

    #[test]
    fn test_memory_type_labels() {
        let m_principle = Memory::new("u", MemoryType::Principle, SensitivityCategory::General, "x");
        let m_preference = Memory::new("u", MemoryType::Preference, SensitivityCategory::General, "x");
        let m_semantic = Memory::new("u", MemoryType::Semantic, SensitivityCategory::General, "x");
        let m_episodic = Memory::new("u", MemoryType::Episodic, SensitivityCategory::General, "x");
        assert_eq!(m_principle.type_label(), "[Principle]");
        assert_eq!(m_preference.type_label(), "[Preference]");
        assert_eq!(m_semantic.type_label(), "[Fact]");
        assert_eq!(m_episodic.type_label(), "[Recent]");
    }

    #[test]
    fn test_iso_now_format() {
        let ts = iso_now();
        // Should be like 2026-06-05T12:34:56Z
        assert_eq!(ts.len(), 20, "iso_now should be 20 chars: {ts}");
        assert!(ts.contains('T'), "should contain T separator: {ts}");
        assert!(ts.ends_with('Z'), "should end with Z: {ts}");
    }

    #[test]
    fn test_unix_secs_to_iso_epoch() {
        // Unix epoch = 1970-01-01T00:00:00Z
        assert_eq!(unix_secs_to_iso(0), "1970-01-01T00:00:00Z");
    }

    #[test]
    fn test_unix_secs_to_iso_known_date() {
        // 2026-06-05T00:00:00Z = 1780272000 seconds after epoch
        // (calculated: (2026-1970)*365.25 + leap years — let's just verify format)
        let ts = unix_secs_to_iso(1780272000);
        assert!(ts.starts_with("2026-"), "expected 2026 date, got: {ts}");
        assert!(ts.ends_with('Z'), "should end with Z: {ts}");
    }

    #[test]
    fn test_new_uuid_is_unique() {
        let a = new_uuid();
        let b = new_uuid();
        assert_ne!(a, b, "UUIDs should be unique");
        assert_eq!(a.len(), 36, "UUID should be 36 chars");
    }

    #[test]
    fn test_memory_serialization() {
        let m = Memory::new("user-bob", MemoryType::Episodic, SensitivityCategory::Work, "attended standup");
        let json = serde_json::to_string(&m).unwrap();
        let deserialized: Memory = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.user_id, "user-bob");
        assert_eq!(deserialized.memory_type, MemoryType::Episodic);
        assert_eq!(deserialized.content, "attended standup");
    }
}
