[ct310]
192.168.0.120 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct214]
192.168.0.226 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct300]
192.168.0.224 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct305]
192.168.0.217 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct223]
192.168.0.223 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct215]
192.168.0.215 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[lumina_fleet:children]
ct310

[lumina_terminus:children]
ct214

[lumina_all:children]
lumina_fleet
lumina_terminus
