[ct310]
YOUR_FLEET_HOST_IP ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct214]
YOUR_TERMINUS_HOST_IP ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct300]
YOUR_POSTGRES_HOST_IP ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct305]
YOUR_IRONCLAW_HOST_IP ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct223]
YOUR_GITEA_HOST_IP ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[ct215]
YOUR_LITELLM_HOST_IP ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[lumina_fleet:children]
ct310

[lumina_terminus:children]
ct214

[lumina_all:children]
lumina_fleet
lumina_terminus
