//! P2-04: Vigil morning briefing engine.
//!
//! [`VigilBriefing`] aggregates data from configured source adapters, builds
//! a prompt from the aggregated text, and returns it ready for LLM generation.
//!
//! ## Design decisions
//!
//! - **LLM generation** — the spec explicitly requires the briefing to be
//!   "generated by the LLM from aggregated data, not templated" so it reads
//!   naturally. This module builds the aggregated context; the caller passes
//!   it to Chord/the agent loop for actual generation.
//!
//! - **Graceful degradation** — if all sources are unavailable the prompt
//!   still asks the LLM to produce a polite fallback message, and the
//!   function always returns a non-empty prompt string.
//!
//! - **No hardcoded values** — locations, IP addresses, usernames, and API
//!   endpoints are strictly forbidden in this file.  Everything comes from
//!   [`BriefingConfig`] and [`UserSettings`].
//!
//! ## Quick start
//!
//! ```rust,no_run
//! use lumina_core::vigil::briefing::VigilBriefing;
//! use lumina_core::vigil::config::BriefingConfig;
//! use lumina_core::vigil::adapters::UserSettings;
//!
//! # tokio_test::block_on(async {
//! let config   = BriefingConfig::from_env();
//! let settings = UserSettings::from_env();
//! let briefing = VigilBriefing::new(config, settings);
//! let prompt   = briefing.build_prompt().await;
//! // Pass `prompt` to your Chord/LLM call to produce the final text.
//! println!("{}", prompt);
//! # })
//! ```

use crate::vigil::adapters::{AdapterRegistry, SourceData, UserSettings};
use crate::vigil::config::{BriefingConfig, DetailLevel};

/// The Vigil morning briefing engine.
///
/// Aggregates data from configured source adapters and builds an LLM prompt
/// that, when sent to a high-quality model, produces a natural morning briefing.
pub struct VigilBriefing {
    config:   BriefingConfig,
    settings: UserSettings,
    registry: AdapterRegistry,
}

impl VigilBriefing {
    /// Create a new `VigilBriefing` with a default adapter registry.
    pub fn new(config: BriefingConfig, settings: UserSettings) -> Self {
        Self {
            config,
            settings,
            registry: AdapterRegistry::default_registry(),
        }
    }

    /// Create a `VigilBriefing` with a custom adapter registry (used for testing).
    pub fn with_registry(
        config:   BriefingConfig,
        settings: UserSettings,
        registry: AdapterRegistry,
    ) -> Self {
        Self { config, settings, registry }
    }

    /// Aggregate data from all configured adapters and return the results.
    ///
    /// Only sources that are both enabled in [`BriefingConfig`] and configured
    /// in [`UserSettings`] are queried.  Disabled sources never make HTTP calls.
    /// Failed or timed-out sources contribute `"unavailable"` entries — they
    /// never cause a panic or error return.
    pub async fn aggregate(&self) -> Vec<SourceData> {
        let enabled: std::collections::HashSet<String> =
            self.config.enabled_sources().into_iter().collect();
        // Only adapters in the enabled set are spawned — disabled sources
        // never make HTTP calls, saving both latency and API quota.
        self.registry.fetch_all_filtered(&self.settings, &enabled).await
    }

    /// Build the LLM generation prompt from aggregated source data.
    ///
    /// The prompt instructs the model to produce a morning briefing with the
    /// appropriate level of detail.  If all sources are unavailable the prompt
    /// requests a polite fallback message.
    ///
    /// This function calls [`aggregate`] internally and applies the
    /// `briefing_timeout_secs` from config (via the adapter registry's own
    /// per-adapter timeout; callers should additionally impose a top-level
    /// timeout on the LLM call).
    pub async fn build_prompt(&self) -> String {
        let data = self.aggregate().await;
        self.compose_prompt(&data)
    }

    /// Compose the LLM prompt from pre-collected [`SourceData`].
    ///
    /// This is `pub` so tests can inject data without running real HTTP calls.
    pub fn compose_prompt(&self, data: &[SourceData]) -> String {
        let name_clause = if self.config.user_name.is_empty() {
            String::new()
        } else {
            format!(" for {}", self.config.user_name)
        };

        let tz_clause = if self.config.timezone == "UTC" || self.config.timezone.is_empty() {
            String::new()
        } else {
            format!(" (timezone: {})", self.config.timezone)
        };

        let detail_instruction = match self.config.detail {
            DetailLevel::Brief =>
                "Be concise — 3 to 4 sentences covering the most important points.",
            DetailLevel::Full =>
                "Provide a detailed briefing with analysis and actionable suggestions. \
                 Use multiple paragraphs if needed.",
        };

        // Separate available vs. unavailable sources using the dedicated flag,
        // not magic string comparison.
        let available: Vec<&SourceData> = data
            .iter()
            .filter(|d| d.available)
            .collect();

        let unavailable: Vec<&str> = data
            .iter()
            .filter(|d| !d.available)
            .map(|d| d.source.as_str())
            .collect();

        if available.is_empty() {
            // All sources unavailable — request a polite fallback.
            return format!(
                "Generate a brief morning greeting{}{}. \
                 Unfortunately, none of the data sources (weather, news, commute, calendar, tasks) \
                 could be reached right now. \
                 Acknowledge this gracefully and suggest the user check back later. \
                 Be warm and brief.",
                name_clause, tz_clause
            );
        }

        // Build the data section.
        let data_section: String = available
            .iter()
            .map(|d| format!("### {}\n{}", capitalise(&d.source), d.summary))
            .collect::<Vec<_>>()
            .join("\n\n");

        let unavailable_note = if unavailable.is_empty() {
            String::new()
        } else {
            format!(
                "\n\nNote: the following sources were unavailable and should be \
                 briefly mentioned: {}.",
                unavailable.join(", ")
            )
        };

        format!(
            "Generate a morning briefing{}{} from the data below.\n\
             {}\n\
             Be direct and conversational. Highlight important items and any \
             actionable suggestions.{}\n\n\
             ---\n\n{}",
            name_clause,
            tz_clause,
            detail_instruction,
            unavailable_note,
            data_section,
        )
    }

    /// Return the cron schedule expression from config.
    ///
    /// Convenience accessor so callers can register the routine without
    /// reaching into the config directly.
    pub fn schedule(&self) -> &str {
        &self.config.schedule
    }

    /// Return the model alias that should be used for LLM generation.
    pub fn llm_model(&self) -> &str {
        &self.config.llm_model
    }

    /// Return the delivery channel name.
    pub fn deliver_channel(&self) -> &str {
        &self.config.deliver_channel
    }

    /// Return the generation timeout in seconds.
    pub fn briefing_timeout_secs(&self) -> u64 {
        self.config.briefing_timeout_secs
    }
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Capitalise the first ASCII character of `s`.
fn capitalise(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

// ── Scheduler routine helper ──────────────────────────────────────────────────

/// Build a `Routine` definition for the morning briefing that can be
/// registered with the background scheduler.
///
/// ## Arguments
///
/// - `config` — the [`BriefingConfig`] controlling schedule, model, channel.
/// - `user_id` — an optional identifier for the user who owns this routine.
///   Because the current [`Routine`] struct has no dedicated `user_id` field,
///   the identifier is embedded in the `prompt` string as `user_id:<id>`.
///   The scheduler's `on_routine` callback can extract this token to look up
///   the correct `BriefingConfig` + `UserSettings` at dispatch time.
///   Pass `None` for a single-user deployment.
///
/// ## Returned routine properties
///
/// - `name = "morning_briefing"` (or `"morning_briefing:{user_id}"` when a
///   user_id is provided, so multiple users' routines are distinguishable)
/// - `schedule` from `config.schedule`
/// - `model_override = Some(config.llm_model.clone())`
/// - `channel` mapped from `config.deliver_channel`
/// - `enabled = true`
///
/// Callers insert this into a [`RoutinesConfig`][crate::scheduler::RoutinesConfig]
/// or write it directly to the scheduler's TOML file.

/// Returns `true` if `s` is a valid user ID token (alphanumeric, `-`, `_` only).
fn is_valid_user_id(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

pub fn make_briefing_routine(
    config: &BriefingConfig,
    user_id: Option<&str>,
) -> crate::scheduler::Routine {
    use crate::scheduler::routine::RoutineChannel;

    let channel = match config.deliver_channel.as_str() {
        "matrix" => RoutineChannel::Matrix,
        "file"   => RoutineChannel::File,
        _        => RoutineChannel::Stdout,
    };

    // Validate user_id to prevent colon/newline injection into routine name
    // and prompt tokens.  IDs with non-alphanumeric-or-dash chars are treated
    // as absent (single-user mode).
    let safe_uid = user_id.and_then(|uid| if is_valid_user_id(uid) { Some(uid) } else { None });

    let (name, prompt) = match safe_uid {
        Some(uid) => (
            format!("morning_briefing:{}", uid),
            format!("Generate and deliver the morning briefing. user_id:{}", uid),
        ),
        None => (
            "morning_briefing".to_string(),
            "Generate and deliver the morning briefing.".to_string(),
        ),
    };

    crate::scheduler::Routine {
        name,
        schedule:       config.schedule.clone(),
        prompt,
        model_override: Some(config.llm_model.clone()),
        channel,
        enabled:        true,
        last_run:       None,
        next_run:       None,
        trigger:        None,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::vigil::adapters::{AdapterRegistry, SourceData, UserSettings};
    use crate::vigil::config::BriefingConfig;
    use crate::scheduler::routine::RoutineChannel;

    // ── compose_prompt ────────────────────────────────────────────────────────

    #[test]
    fn test_prompt_contains_weather_section() {
        let cfg = BriefingConfig {
            sources: "weather,news".to_string(),
            ..Default::default()
        };
        let data = vec![
            SourceData::new("weather", "Sunny, 22°C"),
        ];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(
            prompt.contains("Weather") || prompt.contains("weather"),
            "prompt should reference the weather section, got:\n{}", prompt
        );
        assert!(
            prompt.contains("Sunny, 22°C"),
            "prompt should include weather data, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_contains_commute_section() {
        let cfg = BriefingConfig {
            sources: "commute".to_string(),
            ..Default::default()
        };
        let data = vec![
            SourceData::new("commute", "25 min, light traffic"),
        ];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(
            prompt.contains("25 min, light traffic"),
            "prompt should include commute data"
        );
    }

    #[test]
    fn test_prompt_contains_news_section() {
        let cfg = BriefingConfig::default();
        let data = vec![
            SourceData::new("news", "• Rust 2.0 released (TechNews)"),
        ];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(prompt.contains("Rust 2.0"), "prompt should include news data");
    }

    #[test]
    fn test_prompt_all_sources_unavailable() {
        let cfg = BriefingConfig::default();
        let data = vec![
            SourceData::unavailable("weather"),
            SourceData::unavailable("news"),
        ];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        // Should produce a graceful fallback, not an empty string.
        assert!(!prompt.is_empty(), "prompt must not be empty on all-unavailable data");
        // The fallback should mention the sources being unreachable.
        assert!(
            prompt.to_lowercase().contains("unavailable")
            || prompt.to_lowercase().contains("couldn't")
            || prompt.to_lowercase().contains("could not")
            || prompt.to_lowercase().contains("reach"),
            "fallback prompt should acknowledge unavailable sources, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_empty_data_slice() {
        let cfg = BriefingConfig::default();
        let data: Vec<SourceData> = vec![];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(!prompt.is_empty(), "prompt must not be empty with no data");
    }

    #[test]
    fn test_prompt_with_user_name() {
        let cfg = BriefingConfig {
            user_name: "the operator".to_string(),
            ..Default::default()
        };
        let data = vec![SourceData::new("weather", "Cloudy")];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(
            prompt.contains("the operator"),
            "prompt should include the user's name, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_with_timezone() {
        let cfg = BriefingConfig {
            timezone: "America/Los_Angeles".to_string(),
            ..Default::default()
        };
        let data = vec![SourceData::new("weather", "Foggy")];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(
            prompt.contains("America/Los_Angeles"),
            "prompt should include the timezone, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_detail_brief_instruction() {
        let cfg = BriefingConfig {
            detail: crate::vigil::config::DetailLevel::Brief,
            ..Default::default()
        };
        let data = vec![SourceData::new("weather", "Clear")];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(
            prompt.contains("3 to 4 sentences") || prompt.contains("concise"),
            "brief prompt should include conciseness instruction, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_detail_full_instruction() {
        let cfg = BriefingConfig {
            detail: crate::vigil::config::DetailLevel::Full,
            ..Default::default()
        };
        let data = vec![SourceData::new("weather", "Clear")];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        assert!(
            prompt.contains("detailed") || prompt.contains("actionable"),
            "full prompt should include detail instruction, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_mentions_unavailable_sources() {
        let cfg = BriefingConfig {
            sources: "weather,news".to_string(),
            ..Default::default()
        };
        let data = vec![
            SourceData::new("weather", "Sunny"),
            SourceData::unavailable("news"),
        ];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.compose_prompt(&data);
        // Prompt should note that "news" was unavailable.
        assert!(
            prompt.contains("news"),
            "prompt should mention the unavailable 'news' source, got:\n{}", prompt
        );
    }

    #[test]
    fn test_prompt_disabled_sources_excluded() {
        // Only "weather" is enabled; "news" data should be dropped even if passed in.
        let cfg = BriefingConfig {
            sources: "weather".to_string(),
            ..Default::default()
        };
        let data = vec![
            SourceData::new("weather", "Sunny, 20°C"),
            SourceData::new("news", "Breaking: Rust 2.0"),
        ];
        let b = VigilBriefing::new(cfg, UserSettings::default());
        // compose_prompt itself does not filter by config; it works with what it's given.
        // The filtering happens in aggregate(). Here we verify the prompt contains both
        // since we passed both explicitly — filtering is aggregate()'s responsibility.
        let prompt = b.compose_prompt(&data);
        assert!(prompt.contains("Sunny, 20°C"));
    }

    // ── aggregate ─────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn test_aggregate_empty_when_nothing_configured() {
        let cfg = BriefingConfig::default();
        let settings = UserSettings::default(); // no env vars set → nothing configured
        let b = VigilBriefing::new(cfg, settings);
        let results = b.aggregate().await;
        // Default registry has 3 adapters but none are configured → should be empty.
        assert!(
            results.is_empty(),
            "no adapters configured → aggregate should be empty, got: {:?}",
            results.iter().map(|r| &r.source).collect::<Vec<_>>()
        );
    }

    #[tokio::test]
    async fn test_aggregate_filters_disabled_sources() {
        // Build a registry with a mock adapter, but disable it in config.
        use std::sync::Arc;
        use async_trait::async_trait;
        use crate::error::Result as LResult;
        use crate::vigil::adapters::SourceAdapter;

        struct MockAdapter;
        #[async_trait]
        impl SourceAdapter for MockAdapter {
            fn name(&self) -> &str { "mock" }
            fn is_configured(&self, _: &UserSettings) -> bool { true }
            async fn fetch(&self, _: &UserSettings) -> LResult<SourceData> {
                Ok(SourceData::new("mock", "mock_data"))
            }
        }

        let mut registry = AdapterRegistry::new();
        registry.register(Arc::new(MockAdapter));

        let cfg = BriefingConfig {
            sources: "weather".to_string(), // "mock" is NOT in enabled sources
            ..Default::default()
        };
        let b = VigilBriefing::with_registry(cfg, UserSettings::default(), registry);
        let results = b.aggregate().await;

        assert!(
            results.is_empty(),
            "disabled source 'mock' should not appear in aggregate results"
        );
    }

    #[tokio::test]
    async fn test_aggregate_includes_enabled_source() {
        use std::sync::Arc;
        use async_trait::async_trait;
        use crate::error::Result as LResult;
        use crate::vigil::adapters::SourceAdapter;

        struct MockWeather;
        #[async_trait]
        impl SourceAdapter for MockWeather {
            fn name(&self) -> &str { "weather" }
            fn is_configured(&self, _: &UserSettings) -> bool { true }
            async fn fetch(&self, _: &UserSettings) -> LResult<SourceData> {
                Ok(SourceData::new("weather", "Partly cloudy, 18°C"))
            }
        }

        let mut registry = AdapterRegistry::new();
        registry.register(Arc::new(MockWeather));

        let cfg = BriefingConfig {
            sources: "weather".to_string(),
            ..Default::default()
        };
        let b = VigilBriefing::with_registry(cfg, UserSettings::default(), registry);
        let results = b.aggregate().await;

        assert_eq!(results.len(), 1);
        assert_eq!(results[0].source, "weather");
        assert_eq!(results[0].summary, "Partly cloudy, 18°C");
    }

    // ── build_prompt ──────────────────────────────────────────────────────────

    #[tokio::test]
    async fn test_build_prompt_returns_non_empty_string() {
        let cfg = BriefingConfig::default();
        let b = VigilBriefing::new(cfg, UserSettings::default());
        let prompt = b.build_prompt().await;
        assert!(!prompt.is_empty(), "build_prompt must always return a non-empty string");
    }

    // ── accessor methods ──────────────────────────────────────────────────────

    #[test]
    fn test_schedule_accessor() {
        let cfg = BriefingConfig {
            schedule: "0 8 * * *".to_string(),
            ..Default::default()
        };
        let b = VigilBriefing::new(cfg, UserSettings::default());
        assert_eq!(b.schedule(), "0 8 * * *");
    }

    #[test]
    fn test_llm_model_accessor() {
        let cfg = BriefingConfig {
            llm_model: "lumina-fast".to_string(),
            ..Default::default()
        };
        let b = VigilBriefing::new(cfg, UserSettings::default());
        assert_eq!(b.llm_model(), "lumina-fast");
    }

    #[test]
    fn test_deliver_channel_accessor() {
        let cfg = BriefingConfig {
            deliver_channel: "file".to_string(),
            ..Default::default()
        };
        let b = VigilBriefing::new(cfg, UserSettings::default());
        assert_eq!(b.deliver_channel(), "file");
    }

    #[test]
    fn test_briefing_timeout_accessor() {
        let cfg = BriefingConfig {
            briefing_timeout_secs: 90,
            ..Default::default()
        };
        let b = VigilBriefing::new(cfg, UserSettings::default());
        assert_eq!(b.briefing_timeout_secs(), 90);
    }

    // ── make_briefing_routine ─────────────────────────────────────────────────

    #[test]
    fn test_make_briefing_routine_name_is_morning_briefing() {
        let cfg = BriefingConfig::default();
        let routine = make_briefing_routine(&cfg, None);
        assert_eq!(routine.name, "morning_briefing");
    }

    #[test]
    fn test_make_briefing_routine_with_user_id_includes_id_in_name() {
        let cfg = BriefingConfig::default();
        let routine = make_briefing_routine(&cfg, Some("user-abc"));
        assert_eq!(routine.name, "morning_briefing:user-abc",
            "routine name should embed user_id for multi-user disambiguation");
    }

    #[test]
    fn test_make_briefing_routine_with_user_id_includes_id_in_prompt() {
        let cfg = BriefingConfig::default();
        let routine = make_briefing_routine(&cfg, Some("user-abc"));
        assert!(
            routine.prompt.contains("user_id:user-abc"),
            "prompt should embed user_id for on_routine callback dispatch, got: {}",
            routine.prompt
        );
    }

    #[test]
    fn test_make_briefing_routine_empty_user_id_treated_as_none() {
        let cfg = BriefingConfig::default();
        let routine = make_briefing_routine(&cfg, Some(""));
        assert_eq!(routine.name, "morning_briefing",
            "empty user_id should behave like None");
    }

    #[test]
    fn test_make_briefing_routine_uses_config_schedule() {
        let cfg = BriefingConfig {
            schedule: "0 6 * * 1-5".to_string(),
            ..Default::default()
        };
        let routine = make_briefing_routine(&cfg, None);
        assert_eq!(routine.schedule, "0 6 * * 1-5");
    }

    #[test]
    fn test_make_briefing_routine_uses_config_model() {
        let cfg = BriefingConfig {
            llm_model: "lumina-deep".to_string(),
            ..Default::default()
        };
        let routine = make_briefing_routine(&cfg, None);
        assert_eq!(routine.model_override.as_deref(), Some("lumina-deep"));
    }

    #[test]
    fn test_make_briefing_routine_enabled() {
        let cfg = BriefingConfig::default();
        let routine = make_briefing_routine(&cfg, None);
        assert!(routine.enabled);
    }

    #[test]
    fn test_make_briefing_routine_channel_matrix() {
        let cfg = BriefingConfig {
            deliver_channel: "matrix".to_string(),
            ..Default::default()
        };
        let routine = make_briefing_routine(&cfg, None);
        assert_eq!(routine.channel, RoutineChannel::Matrix);
    }

    #[test]
    fn test_make_briefing_routine_channel_file() {
        let cfg = BriefingConfig {
            deliver_channel: "file".to_string(),
            ..Default::default()
        };
        let routine = make_briefing_routine(&cfg, None);
        assert_eq!(routine.channel, RoutineChannel::File);
    }

    #[test]
    fn test_make_briefing_routine_channel_stdout_fallback() {
        let cfg = BriefingConfig {
            deliver_channel: "unknown_channel".to_string(),
            ..Default::default()
        };
        let routine = make_briefing_routine(&cfg, None);
        assert_eq!(routine.channel, RoutineChannel::Stdout);
    }

    #[test]
    fn test_make_briefing_routine_no_trigger() {
        // Cron-based — no event trigger.
        let cfg = BriefingConfig::default();
        let routine = make_briefing_routine(&cfg, None);
        assert!(routine.trigger.is_none());
    }
}
