//! P2-05: Vigil evening summary and next-day prep.
//!
//! [`EveningSummary`] compiles a user's day from audit log entries, previews
//! tomorrow's calendar events, and surfaces unresolved items from memory.
//! The compiled context is formatted as an LLM prompt; the caller passes it to
//! Chord for generation.
//!
//! ## Design decisions
//!
//! - **LLM generation** — per the spec the summary is generated by the LLM
//!   from aggregated data, consistent with the morning briefing approach.
//!   This module builds the context prompt; generation is the caller's
//!   responsibility.
//!
//! - **Graceful degradation** — if no activity exists ("quiet day") the prompt
//!   still produces a useful response focusing on tomorrow.
//!
//! - **No hardcoded values** — all config comes from [`EveningConfig`] and
//!   caller-supplied data slices.  No IPs, hostnames, or personal data.
//!
//! ## Quick start
//!
//! ```rust,no_run
//! use lumina_core::vigil::evening::{EveningSummary, EveningConfig};
//!
//! let config = EveningConfig::from_env();
//! let summary = EveningSummary::new(config);
//!
//! // Supply data gathered elsewhere (audit log, calendar, memory)
//! let completed_tasks = vec!["Reviewed PR #42".to_string(), "Sent status update".to_string()];
//! let tomorrow_events = vec!["Team standup at 09:00".to_string()];
//! let unresolved     = vec!["Follow up on vendor quote".to_string()];
//!
//! let prompt = summary.compose_prompt(&completed_tasks, &tomorrow_events, &unresolved);
//! // Pass `prompt` to your Chord/LLM call to produce the final text.
//! println!("{}", prompt);
//! ```

use crate::vigil::config::BriefingConfig;

// ── EveningConfig ─────────────────────────────────────────────────────────────

/// Per-user configuration for the evening summary routine.
///
/// ## Environment variables
///
/// | Variable                      | Default         | Description                              |
/// |-------------------------------|-----------------|------------------------------------------|
/// | `VIGIL_EVENING_SCHEDULE`      | `"0 20 * * *"`  | Cron for evening delivery (default 8pm)  |
/// | `VIGIL_EVENING_USER_NAME`     | `""`            | Display name used in the summary prompt  |
/// | `VIGIL_EVENING_TIMEZONE`      | `"UTC"`         | User's timezone (IANA)                   |
/// | `VIGIL_EVENING_LLM_MODEL`     | `"lumina-deep"` | Model alias for generation               |
/// | `VIGIL_EVENING_DELIVER_CHANNEL` | `"matrix"`    | Delivery channel name                    |
/// | `VIGIL_EVENING_ENABLED`       | `"true"`        | Set `"false"` to disable the routine     |
#[derive(Debug, Clone)]
pub struct EveningConfig {
    /// Cron expression controlling when the summary fires (default: 8pm daily).
    pub schedule: String,

    /// The user's display name, injected into the generation prompt.
    pub user_name: String,

    /// IANA timezone name (e.g. `"America/Los_Angeles"`).
    pub timezone: String,

    /// Model alias passed to the Chord request.
    pub llm_model: String,

    /// Delivery channel name (e.g. `"matrix"`).
    pub deliver_channel: String,

    /// Whether the evening summary routine is enabled.
    ///
    /// When `false`, [`make_evening_routine`] returns a routine with
    /// `enabled = false` so the scheduler skips it.
    pub enabled: bool,
}

impl Default for EveningConfig {
    fn default() -> Self {
        Self {
            schedule:        "0 20 * * *".to_string(),
            user_name:       String::new(),
            timezone:        "UTC".to_string(),
            llm_model:       "lumina-deep".to_string(),
            deliver_channel: "matrix".to_string(),
            enabled:         true,
        }
    }
}

impl EveningConfig {
    /// Load configuration from environment variables.
    ///
    /// Missing variables use their defaults; no variable is required.
    pub fn from_env() -> Self {
        use std::env;
        let mut cfg = Self::default();

        if let Ok(v) = env::var("VIGIL_EVENING_SCHEDULE") {
            if !v.is_empty() {
                cfg.schedule = v;
            }
        }
        if let Ok(v) = env::var("VIGIL_EVENING_USER_NAME") {
            cfg.user_name = v; // intentionally allow empty
        }
        if let Ok(v) = env::var("VIGIL_EVENING_TIMEZONE") {
            if !v.is_empty() {
                cfg.timezone = v;
            }
        }
        if let Ok(v) = env::var("VIGIL_EVENING_LLM_MODEL") {
            if !v.is_empty() {
                cfg.llm_model = v;
            }
        }
        if let Ok(v) = env::var("VIGIL_EVENING_DELIVER_CHANNEL") {
            if !v.is_empty() {
                cfg.deliver_channel = v;
            }
        }
        if let Ok(v) = env::var("VIGIL_EVENING_ENABLED") {
            cfg.enabled = !matches!(v.trim().to_lowercase().as_str(), "false" | "0" | "no");
        }

        cfg
    }
}

// ── EveningSummary ────────────────────────────────────────────────────────────

/// The Vigil evening summary engine.
///
/// Compiles today's completed tasks, tomorrow's calendar preview, and any
/// unresolved items into an LLM prompt that produces a natural evening
/// reflection and next-day prep message.
pub struct EveningSummary {
    config: EveningConfig,
}

impl EveningSummary {
    /// Create a new `EveningSummary` with the given config.
    pub fn new(config: EveningConfig) -> Self {
        Self { config }
    }

    /// Build an `EveningSummary` using morning briefing config conventions for
    /// shared fields (user_name, timezone, llm_model, deliver_channel).
    ///
    /// Evening-specific env vars (`VIGIL_EVENING_SCHEDULE`, `VIGIL_EVENING_ENABLED`)
    /// are still read, so callers get consistent env-var behaviour regardless of
    /// which constructor they use.  This constructor is useful when callers hold a
    /// `BriefingConfig` and want a matching evening config without duplicating
    /// all env-var reads.
    pub fn from_briefing_config(morning: &BriefingConfig) -> Self {
        let evening_schedule = std::env::var("VIGIL_EVENING_SCHEDULE")
            .ok()
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "0 20 * * *".to_string());

        let enabled = std::env::var("VIGIL_EVENING_ENABLED")
            .map(|v| !matches!(v.trim().to_lowercase().as_str(), "false" | "0" | "no"))
            .unwrap_or(true);

        let config = EveningConfig {
            schedule:        evening_schedule,
            user_name:       morning.user_name.clone(),
            timezone:        morning.timezone.clone(),
            llm_model:       morning.llm_model.clone(),
            deliver_channel: morning.deliver_channel.clone(),
            enabled,
        };
        Self { config }
    }

    /// Compose the LLM prompt from pre-collected data slices.
    ///
    /// All three slices may be empty — the function always returns a non-empty
    /// prompt that gracefully handles the "quiet day" case.
    ///
    /// ## Arguments
    ///
    /// - `completed_tasks` — tasks or conversations completed today (from audit log).
    /// - `tomorrow_events` — calendar events scheduled for tomorrow.
    /// - `unresolved`      — unresolved reminders or action items from memory.
    pub fn compose_prompt(
        &self,
        completed_tasks: &[String],
        tomorrow_events: &[String],
        unresolved: &[String],
    ) -> String {
        let name_clause = if self.config.user_name.is_empty() {
            String::new()
        } else {
            format!(" for {}", self.config.user_name)
        };

        let tz_clause = if self.config.timezone == "UTC" || self.config.timezone.is_empty() {
            String::new()
        } else {
            format!(" (timezone: {})", self.config.timezone)
        };

        // ── Today section ─────────────────────────────────────────────────────
        let today_section = if completed_tasks.is_empty() {
            "Today was quiet — no recorded activity.".to_string()
        } else {
            let items = completed_tasks
                .iter()
                .map(|t| format!("- {}", t))
                .collect::<Vec<_>>()
                .join("\n");
            format!("Completed today:\n{}", items)
        };

        // ── Tomorrow section ──────────────────────────────────────────────────
        let tomorrow_section = if tomorrow_events.is_empty() {
            "No calendar events scheduled for tomorrow.".to_string()
        } else {
            let items = tomorrow_events
                .iter()
                .map(|e| format!("- {}", e))
                .collect::<Vec<_>>()
                .join("\n");
            format!("Tomorrow's calendar:\n{}", items)
        };

        // ── Unresolved section ────────────────────────────────────────────────
        let unresolved_section = if unresolved.is_empty() {
            String::new()
        } else {
            let items = unresolved
                .iter()
                .map(|u| format!("- {}", u))
                .collect::<Vec<_>>()
                .join("\n");
            format!("\nUnresolved items:\n{}", items)
        };

        format!(
            "Generate an evening summary{}{} from the data below.\n\
             Be brief, reflective, and helpful. Acknowledge the day's work, \
             preview tomorrow, and surface any unresolved items that need attention.\n\n\
             ---\n\n\
             {}\n\n\
             {}\
             {}",
            name_clause,
            tz_clause,
            today_section,
            tomorrow_section,
            unresolved_section,
        )
    }

    /// Return the cron schedule expression from config.
    pub fn schedule(&self) -> &str {
        &self.config.schedule
    }

    /// Return the model alias for LLM generation.
    pub fn llm_model(&self) -> &str {
        &self.config.llm_model
    }

    /// Return the delivery channel name.
    pub fn deliver_channel(&self) -> &str {
        &self.config.deliver_channel
    }

    /// Return `true` if this summary routine is enabled.
    pub fn is_enabled(&self) -> bool {
        self.config.enabled
    }
}

// ── Scheduler routine helper ──────────────────────────────────────────────────

/// Returns `true` if `s` is a valid user ID token (alphanumeric, `-`, `_` only).
fn is_valid_user_id(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// Build a `Routine` definition for the evening summary that can be registered
/// with the background scheduler.
///
/// ## Arguments
///
/// - `config`  — the [`EveningConfig`] controlling schedule, model, channel.
/// - `user_id` — optional identifier for the user who owns this routine.
///   Embedded in the routine name and prompt as `user_id:<id>` so the
///   scheduler's `on_routine` callback can dispatch to the correct config.
///   Pass `None` for a single-user deployment.
///
/// ## Returned routine properties
///
/// - `name = "evening_summary"` (or `"evening_summary:{user_id}"`)
/// - `schedule` from `config.schedule` — default `"0 20 * * *"` (8pm daily)
/// - `model_override = Some(config.llm_model.clone())`
/// - `channel` mapped from `config.deliver_channel`
/// - `enabled` from `config.enabled`
pub fn make_evening_routine(
    config: &EveningConfig,
    user_id: Option<&str>,
) -> crate::scheduler::Routine {
    use crate::scheduler::routine::RoutineChannel;

    let channel = match config.deliver_channel.as_str() {
        "matrix" => RoutineChannel::Matrix,
        "file"   => RoutineChannel::File,
        _        => RoutineChannel::Stdout,
    };

    // Validate user_id to prevent colon/newline injection into routine name
    // and prompt tokens.
    let safe_uid = user_id.and_then(|uid| if is_valid_user_id(uid) { Some(uid) } else { None });

    let (name, prompt) = match safe_uid {
        Some(uid) => (
            format!("evening_summary:{}", uid),
            format!("Generate and deliver the evening summary. user_id:{}", uid),
        ),
        None => (
            "evening_summary".to_string(),
            "Generate and deliver the evening summary.".to_string(),
        ),
    };

    crate::scheduler::Routine {
        name,
        schedule:       config.schedule.clone(),
        prompt,
        model_override: Some(config.llm_model.clone()),
        channel,
        enabled:        config.enabled,
        last_run:       None,
        next_run:       None,
        trigger:        None,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;
    use crate::scheduler::routine::RoutineChannel;
    use std::sync::Mutex;

    /// Serialise all tests that mutate process-global env vars.
    /// Must be module-level so every test shares the same mutex instance.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    // ── compose_prompt — task list ────────────────────────────────────────────

    #[test]
    fn test_summary_contains_completed_tasks() {
        let cfg = EveningConfig::default();
        let summary = EveningSummary::new(cfg);
        let tasks = vec![
            "Reviewed PR #42".to_string(),
            "Sent weekly status update".to_string(),
        ];
        let prompt = summary.compose_prompt(&tasks, &[], &[]);
        assert!(
            prompt.contains("Reviewed PR #42"),
            "prompt should contain first completed task, got:\n{}", prompt
        );
        assert!(
            prompt.contains("Sent weekly status update"),
            "prompt should contain second completed task, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_handles_empty_task_list() {
        let cfg = EveningConfig::default();
        let summary = EveningSummary::new(cfg);
        let prompt = summary.compose_prompt(&[], &[], &[]);
        // Must not be empty and must acknowledge the quiet day.
        assert!(!prompt.is_empty(), "prompt must not be empty for empty task list");
        assert!(
            prompt.to_lowercase().contains("quiet") || prompt.to_lowercase().contains("no recorded"),
            "prompt should acknowledge quiet/no-activity day, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_contains_tomorrow_events() {
        let cfg = EveningConfig::default();
        let summary = EveningSummary::new(cfg);
        let tomorrow = vec!["Team standup at 09:00".to_string()];
        let prompt = summary.compose_prompt(&[], &tomorrow, &[]);
        assert!(
            prompt.contains("Team standup at 09:00"),
            "prompt should include tomorrow's calendar events, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_notes_no_tomorrow_events() {
        let cfg = EveningConfig::default();
        let summary = EveningSummary::new(cfg);
        let prompt = summary.compose_prompt(&[], &[], &[]);
        assert!(
            prompt.to_lowercase().contains("no calendar") || prompt.to_lowercase().contains("no events"),
            "prompt should note absence of tomorrow events, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_contains_unresolved_items() {
        let cfg = EveningConfig::default();
        let summary = EveningSummary::new(cfg);
        let unresolved = vec!["Follow up on vendor quote".to_string()];
        let prompt = summary.compose_prompt(&[], &[], &unresolved);
        assert!(
            prompt.contains("Follow up on vendor quote"),
            "prompt should surface unresolved items, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_no_unresolved_section_when_empty() {
        let cfg = EveningConfig::default();
        let summary = EveningSummary::new(cfg);
        let prompt = summary.compose_prompt(&["Done something".to_string()], &[], &[]);
        // The unresolved section header should not appear when list is empty.
        assert!(
            !prompt.contains("Unresolved items:"),
            "prompt should not include unresolved section when list is empty, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_with_user_name() {
        let cfg = EveningConfig {
            user_name: "the operator".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::new(cfg);
        let prompt = summary.compose_prompt(&[], &[], &[]);
        assert!(
            prompt.contains("the operator"),
            "prompt should include the user's name, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_with_timezone() {
        let cfg = EveningConfig {
            timezone: "America/Chicago".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::new(cfg);
        let prompt = summary.compose_prompt(&[], &[], &[]);
        assert!(
            prompt.contains("America/Chicago"),
            "prompt should include the timezone, got:\n{}", prompt
        );
    }

    #[test]
    fn test_summary_utc_timezone_not_repeated() {
        // UTC is the default and should not appear as an explicit tz clause.
        let cfg = EveningConfig {
            timezone: "UTC".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::new(cfg);
        let prompt = summary.compose_prompt(&[], &[], &[]);
        assert!(
            !prompt.contains("timezone: UTC"),
            "UTC timezone clause should be omitted from prompt, got:\n{}", prompt
        );
    }

    // ── EveningConfig defaults ────────────────────────────────────────────────

    #[test]
    fn test_default_schedule_is_8pm() {
        let cfg = EveningConfig::default();
        assert_eq!(cfg.schedule, "0 20 * * *",
            "default evening schedule should be 8pm daily");
    }

    #[test]
    fn test_default_config_enabled() {
        assert!(EveningConfig::default().enabled);
    }

    #[test]
    fn test_default_llm_model() {
        assert_eq!(EveningConfig::default().llm_model, "lumina-deep");
    }

    // ── make_evening_routine ──────────────────────────────────────────────────

    #[test]
    fn test_make_evening_routine_schedule_is_8pm() {
        let cfg = EveningConfig::default();
        let routine = make_evening_routine(&cfg, None);
        assert_eq!(routine.schedule, "0 20 * * *",
            "routine schedule must be 8pm daily");
    }

    #[test]
    fn test_make_evening_routine_name() {
        let cfg = EveningConfig::default();
        let routine = make_evening_routine(&cfg, None);
        assert_eq!(routine.name, "evening_summary");
    }

    #[test]
    fn test_make_evening_routine_with_user_id() {
        let cfg = EveningConfig::default();
        let routine = make_evening_routine(&cfg, Some("user-42"));
        assert_eq!(routine.name, "evening_summary:user-42");
        assert!(
            routine.prompt.contains("user_id:user-42"),
            "prompt should embed user_id, got: {}", routine.prompt
        );
    }

    #[test]
    fn test_make_evening_routine_invalid_user_id_treated_as_none() {
        let cfg = EveningConfig::default();
        let routine = make_evening_routine(&cfg, Some("bad:id"));
        assert_eq!(routine.name, "evening_summary",
            "invalid user_id with colon should be treated as None");
    }

    #[test]
    fn test_make_evening_routine_empty_user_id_treated_as_none() {
        let cfg = EveningConfig::default();
        let routine = make_evening_routine(&cfg, Some(""));
        assert_eq!(routine.name, "evening_summary",
            "empty user_id should behave like None");
    }

    #[test]
    fn test_make_evening_routine_channel_matrix() {
        let cfg = EveningConfig {
            deliver_channel: "matrix".to_string(),
            ..Default::default()
        };
        let routine = make_evening_routine(&cfg, None);
        assert_eq!(routine.channel, RoutineChannel::Matrix);
    }

    #[test]
    fn test_make_evening_routine_channel_file() {
        let cfg = EveningConfig {
            deliver_channel: "file".to_string(),
            ..Default::default()
        };
        let routine = make_evening_routine(&cfg, None);
        assert_eq!(routine.channel, RoutineChannel::File);
    }

    #[test]
    fn test_make_evening_routine_channel_stdout_fallback() {
        let cfg = EveningConfig {
            deliver_channel: "unknown".to_string(),
            ..Default::default()
        };
        let routine = make_evening_routine(&cfg, None);
        assert_eq!(routine.channel, RoutineChannel::Stdout);
    }

    #[test]
    fn test_make_evening_routine_enabled_true() {
        let cfg = EveningConfig { enabled: true, ..Default::default() };
        assert!(make_evening_routine(&cfg, None).enabled);
    }

    #[test]
    fn test_make_evening_routine_enabled_false() {
        let cfg = EveningConfig { enabled: false, ..Default::default() };
        assert!(!make_evening_routine(&cfg, None).enabled);
    }

    #[test]
    fn test_make_evening_routine_uses_config_model() {
        let cfg = EveningConfig {
            llm_model: "lumina-fast".to_string(),
            ..Default::default()
        };
        let routine = make_evening_routine(&cfg, None);
        assert_eq!(routine.model_override.as_deref(), Some("lumina-fast"));
    }

    #[test]
    fn test_make_evening_routine_no_trigger() {
        let cfg = EveningConfig::default();
        let routine = make_evening_routine(&cfg, None);
        assert!(routine.trigger.is_none(), "cron-based routine should have no event trigger");
    }

    // ── accessor methods ──────────────────────────────────────────────────────

    #[test]
    fn test_schedule_accessor() {
        let cfg = EveningConfig {
            schedule: "0 21 * * *".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::new(cfg);
        assert_eq!(summary.schedule(), "0 21 * * *");
    }

    #[test]
    fn test_llm_model_accessor() {
        let cfg = EveningConfig {
            llm_model: "lumina-fast".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::new(cfg);
        assert_eq!(summary.llm_model(), "lumina-fast");
    }

    #[test]
    fn test_deliver_channel_accessor() {
        let cfg = EveningConfig {
            deliver_channel: "file".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::new(cfg);
        assert_eq!(summary.deliver_channel(), "file");
    }

    #[test]
    fn test_is_enabled_true() {
        let summary = EveningSummary::new(EveningConfig::default());
        assert!(summary.is_enabled());
    }

    #[test]
    fn test_is_enabled_false() {
        let cfg = EveningConfig { enabled: false, ..Default::default() };
        let summary = EveningSummary::new(cfg);
        assert!(!summary.is_enabled());
    }

    // ── from_briefing_config ──────────────────────────────────────────────────

    #[test]
    fn test_from_briefing_config_inherits_user_name() {
        use crate::vigil::config::BriefingConfig;
        let morning = BriefingConfig {
            user_name: "Alice".to_string(),
            ..Default::default()
        };
        let summary = EveningSummary::from_briefing_config(&morning);
        assert_eq!(summary.config.user_name, "Alice");
    }

    #[test]
    #[serial]
    fn test_from_briefing_config_default_schedule_is_8pm() {
        let _g = ENV_LOCK.lock().unwrap();
        std::env::remove_var("VIGIL_EVENING_SCHEDULE");
        use crate::vigil::config::BriefingConfig;
        let morning = BriefingConfig::default();
        let summary = EveningSummary::from_briefing_config(&morning);
        // Without VIGIL_EVENING_SCHEDULE set, should default to 8pm.
        assert_eq!(summary.config.schedule, "0 20 * * *");
        std::env::remove_var("VIGIL_EVENING_SCHEDULE");
    }

    #[test]
    #[serial]
    fn test_from_briefing_config_respects_enabled_env_var() {
        let _g = ENV_LOCK.lock().unwrap();
        std::env::set_var("VIGIL_EVENING_ENABLED", "false");
        use crate::vigil::config::BriefingConfig;
        let morning = BriefingConfig::default();
        let summary = EveningSummary::from_briefing_config(&morning);
        assert!(!summary.config.enabled,
            "from_briefing_config should honour VIGIL_EVENING_ENABLED=false");
        std::env::remove_var("VIGIL_EVENING_ENABLED");
    }

    // ── EveningConfig::from_env ───────────────────────────────────────────────

    #[test]
    #[serial]
    fn test_from_env_defaults_when_nothing_set() {
        let _g = ENV_LOCK.lock().unwrap();

        let keys = [
            "VIGIL_EVENING_SCHEDULE", "VIGIL_EVENING_USER_NAME",
            "VIGIL_EVENING_TIMEZONE", "VIGIL_EVENING_LLM_MODEL",
            "VIGIL_EVENING_DELIVER_CHANNEL", "VIGIL_EVENING_ENABLED",
        ];
        for k in &keys { std::env::remove_var(k); }

        let cfg = EveningConfig::from_env();
        assert_eq!(cfg.schedule, "0 20 * * *");
        assert_eq!(cfg.llm_model, "lumina-deep");
        assert_eq!(cfg.timezone, "UTC");
        assert!(cfg.enabled);

        for k in &keys { std::env::remove_var(k); }
    }

    #[test]
    #[serial]
    fn test_from_env_reads_schedule() {
        let _g = ENV_LOCK.lock().unwrap();

        std::env::set_var("VIGIL_EVENING_SCHEDULE", "0 21 * * *");
        let cfg = EveningConfig::from_env();
        assert_eq!(cfg.schedule, "0 21 * * *");
        std::env::remove_var("VIGIL_EVENING_SCHEDULE");
    }

    #[test]
    #[serial]
    fn test_from_env_disabled_flag() {
        let _g = ENV_LOCK.lock().unwrap();

        std::env::set_var("VIGIL_EVENING_ENABLED", "false");
        let cfg = EveningConfig::from_env();
        assert!(!cfg.enabled);
        std::env::remove_var("VIGIL_EVENING_ENABLED");
    }
}
